-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:b9294e3c2ce5e868aa0237c236337994$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "run-0_rgb_001.png",
				spriteColorRect = { x = 151, y = 111, width = 114, height = 178 },
				textureRect = { x = 114, y = 808, width = 114, height = 178 },
				spriteSourceSize = { width = 114, height = 178 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_003.png",
				spriteColorRect = { x = 150, y = 123, width = 114, height = 164 },
				textureRect = { x = 642, y = 434, width = 114, height = 164 },
				spriteSourceSize = { width = 114, height = 164 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_009.png",
				spriteColorRect = { x = 150, y = 123, width = 112, height = 172 },
				textureRect = { x = 344, y = 730, width = 112, height = 172 },
				spriteSourceSize = { width = 112, height = 172 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_011.png",
				spriteColorRect = { x = 150, y = 123, width = 112, height = 172 },
				textureRect = { x = 230, y = 776, width = 112, height = 172 },
				spriteSourceSize = { width = 112, height = 172 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_017.png",
				spriteColorRect = { x = 151, y = 116, width = 106, height = 164 },
				textureRect = { x = 458, y = 852, width = 106, height = 164 },
				spriteSourceSize = { width = 106, height = 164 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_025.png",
				spriteColorRect = { x = 150, y = 99, width = 110, height = 180 },
				textureRect = { x = 912, y = 434, width = 110, height = 180 },
				spriteSourceSize = { width = 110, height = 180 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_033.png",
				spriteColorRect = { x = 150, y = 97, width = 110, height = 188 },
				textureRect = { x = 2, y = 816, width = 110, height = 188 },
				spriteSourceSize = { width = 110, height = 188 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_001.png",
				spriteColorRect = { x = 96, y = 127, width = 170, height = 136 },
				textureRect = { x = 182, y = 138, width = 170, height = 136 },
				spriteSourceSize = { width = 170, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_003.png",
				spriteColorRect = { x = 98, y = 130, width = 168, height = 136 },
				textureRect = { x = 354, y = 146, width = 168, height = 136 },
				spriteSourceSize = { width = 168, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_009.png",
				spriteColorRect = { x = 107, y = 131, width = 158, height = 138 },
				textureRect = { x = 670, y = 292, width = 158, height = 138 },
				spriteSourceSize = { width = 158, height = 138 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_011.png",
				spriteColorRect = { x = 110, y = 130, width = 156, height = 138 },
				textureRect = { x = 484, y = 434, width = 156, height = 138 },
				spriteSourceSize = { width = 156, height = 138 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_017.png",
				spriteColorRect = { x = 113, y = 129, width = 158, height = 126 },
				textureRect = { x = 324, y = 428, width = 158, height = 126 },
				spriteSourceSize = { width = 158, height = 126 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_025.png",
				spriteColorRect = { x = 111, y = 120, width = 168, height = 132 },
				textureRect = { x = 172, y = 276, width = 168, height = 132 },
				spriteSourceSize = { width = 168, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_033.png",
				spriteColorRect = { x = 100, y = 121, width = 182, height = 134 },
				textureRect = { x = 182, y = 2, width = 182, height = 134 },
				spriteSourceSize = { width = 182, height = 134 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_001.png",
				spriteColorRect = { x = 151, y = 83, width = 114, height = 174 },
				textureRect = { x = 228, y = 600, width = 114, height = 174 },
				spriteSourceSize = { width = 114, height = 174 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_003.png",
				spriteColorRect = { x = 151, y = 85, width = 114, height = 172 },
				textureRect = { x = 344, y = 556, width = 114, height = 172 },
				spriteSourceSize = { width = 114, height = 172 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_009.png",
				spriteColorRect = { x = 151, y = 90, width = 112, height = 166 },
				textureRect = { x = 766, y = 724, width = 112, height = 166 },
				spriteSourceSize = { width = 112, height = 166 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_011.png",
				spriteColorRect = { x = 152, y = 91, width = 110, height = 166 },
				textureRect = { x = 912, y = 616, width = 110, height = 166 },
				spriteSourceSize = { width = 110, height = 166 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_017.png",
				spriteColorRect = { x = 151, y = 95, width = 108, height = 168 },
				textureRect = { x = 880, y = 784, width = 108, height = 168 },
				spriteSourceSize = { width = 108, height = 168 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_025.png",
				spriteColorRect = { x = 150, y = 92, width = 112, height = 184 },
				textureRect = { x = 114, y = 622, width = 112, height = 184 },
				spriteSourceSize = { width = 112, height = 184 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_033.png",
				spriteColorRect = { x = 151, y = 87, width = 110, height = 192 },
				textureRect = { x = 2, y = 622, width = 110, height = 192 },
				spriteSourceSize = { width = 110, height = 192 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_001.png",
				spriteColorRect = { x = 105, y = 98, width = 158, height = 154 },
				textureRect = { x = 2, y = 312, width = 158, height = 154 },
				spriteSourceSize = { width = 158, height = 154 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_003.png",
				spriteColorRect = { x = 107, y = 99, width = 156, height = 152 },
				textureRect = { x = 2, y = 468, width = 156, height = 152 },
				spriteSourceSize = { width = 156, height = 152 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_009.png",
				spriteColorRect = { x = 115, y = 107, width = 148, height = 144 },
				textureRect = { x = 460, y = 574, width = 148, height = 144 },
				spriteSourceSize = { width = 148, height = 144 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_011.png",
				spriteColorRect = { x = 117, y = 109, width = 146, height = 142 },
				textureRect = { x = 610, y = 600, width = 146, height = 142 },
				spriteSourceSize = { width = 146, height = 142 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_017.png",
				spriteColorRect = { x = 123, y = 115, width = 142, height = 136 },
				textureRect = { x = 878, y = 2, width = 142, height = 136 },
				spriteSourceSize = { width = 142, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_025.png",
				spriteColorRect = { x = 118, y = 114, width = 166, height = 140 },
				textureRect = { x = 694, y = 150, width = 166, height = 140 },
				spriteSourceSize = { width = 166, height = 140 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_033.png",
				spriteColorRect = { x = 108, y = 101, width = 178, height = 152 },
				textureRect = { x = 2, y = 2, width = 178, height = 152 },
				spriteSourceSize = { width = 178, height = 152 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_001.png",
				spriteColorRect = { x = 127, y = 107, width = 166, height = 146 },
				textureRect = { x = 710, y = 2, width = 166, height = 146 },
				spriteSourceSize = { width = 166, height = 146 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_003.png",
				spriteColorRect = { x = 142, y = 108, width = 152, height = 144 },
				textureRect = { x = 758, y = 434, width = 152, height = 144 },
				spriteSourceSize = { width = 152, height = 144 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_009.png",
				spriteColorRect = { x = 143, y = 116, width = 160, height = 134 },
				textureRect = { x = 830, y = 298, width = 160, height = 134 },
				spriteSourceSize = { width = 160, height = 134 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_011.png",
				spriteColorRect = { x = 142, y = 114, width = 160, height = 136 },
				textureRect = { x = 162, y = 410, width = 160, height = 136 },
				spriteSourceSize = { width = 160, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_017.png",
				spriteColorRect = { x = 139, y = 122, width = 148, height = 130 },
				textureRect = { x = 460, y = 720, width = 148, height = 130 },
				spriteSourceSize = { width = 148, height = 130 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_025.png",
				spriteColorRect = { x = 121, y = 121, width = 164, height = 142 },
				textureRect = { x = 342, y = 284, width = 164, height = 142 },
				spriteSourceSize = { width = 164, height = 142 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_033.png",
				spriteColorRect = { x = 120, y = 110, width = 168, height = 154 },
				textureRect = { x = 2, y = 156, width = 168, height = 154 },
				spriteSourceSize = { width = 168, height = 154 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_001.png",
				spriteColorRect = { x = 125, y = 124, width = 168, height = 144 },
				textureRect = { x = 540, y = 2, width = 168, height = 144 },
				spriteSourceSize = { width = 168, height = 144 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_003.png",
				spriteColorRect = { x = 142, y = 129, width = 152, height = 142 },
				textureRect = { x = 758, y = 580, width = 152, height = 142 },
				spriteSourceSize = { width = 152, height = 142 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_009.png",
				spriteColorRect = { x = 143, y = 130, width = 160, height = 146 },
				textureRect = { x = 862, y = 150, width = 160, height = 146 },
				spriteSourceSize = { width = 160, height = 146 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_011.png",
				spriteColorRect = { x = 143, y = 132, width = 160, height = 144 },
				textureRect = { x = 508, y = 288, width = 160, height = 144 },
				spriteSourceSize = { width = 160, height = 144 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_017.png",
				spriteColorRect = { x = 133, y = 130, width = 154, height = 130 },
				textureRect = { x = 610, y = 744, width = 154, height = 130 },
				spriteSourceSize = { width = 154, height = 130 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_025.png",
				spriteColorRect = { x = 117, y = 119, width = 168, height = 138 },
				textureRect = { x = 524, y = 148, width = 168, height = 138 },
				spriteSourceSize = { width = 168, height = 138 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_033.png",
				spriteColorRect = { x = 116, y = 119, width = 172, height = 142 },
				textureRect = { x = 366, y = 2, width = 172, height = 142 },
				spriteSourceSize = { width = 172, height = 142 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

