-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:92972a0bca73196c1377571eb401e1b6$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "run-160_rgb_001.png",
				spriteColorRect = { x = 121, y = 138, width = 155, height = 119 },
				textureRect = { x = 1169, y = 135, width = 155, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_003.png",
				spriteColorRect = { x = 121, y = 146, width = 155, height = 113 },
				textureRect = { x = 992, y = 141, width = 155, height = 113 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_009.png",
				spriteColorRect = { x = 128, y = 147, width = 147, height = 115 },
				textureRect = { x = 2, y = 1108, width = 147, height = 115 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_011.png",
				spriteColorRect = { x = 129, y = 147, width = 147, height = 115 },
				textureRect = { x = 268, y = 948, width = 147, height = 115 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_017.png",
				spriteColorRect = { x = 136, y = 136, width = 145, height = 113 },
				textureRect = { x = 2, y = 1465, width = 145, height = 113 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_025.png",
				spriteColorRect = { x = 130, y = 142, width = 159, height = 103 },
				textureRect = { x = 553, y = 216, width = 159, height = 103 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_033.png",
				spriteColorRect = { x = 122, y = 142, width = 169, height = 107 },
				textureRect = { x = 829, y = 2, width = 169, height = 107 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_001.png",
				spriteColorRect = { x = 129, y = 111, width = 145, height = 135 },
				textureRect = { x = 2, y = 1328, width = 145, height = 135 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_003.png",
				spriteColorRect = { x = 130, y = 112, width = 143, height = 133 },
				textureRect = { x = 1752, y = 668, width = 143, height = 133 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_009.png",
				spriteColorRect = { x = 132, y = 112, width = 141, height = 133 },
				textureRect = { x = 1724, y = 803, width = 141, height = 133 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_011.png",
				spriteColorRect = { x = 136, y = 114, width = 137, height = 131 },
				textureRect = { x = 1096, y = 1275, width = 137, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_017.png",
				spriteColorRect = { x = 142, y = 118, width = 133, height = 127 },
				textureRect = { x = 413, y = 1213, width = 133, height = 127 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_025.png",
				spriteColorRect = { x = 135, y = 114, width = 159, height = 133 },
				textureRect = { x = 277, y = 129, width = 159, height = 133 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_033.png",
				spriteColorRect = { x = 128, y = 110, width = 167, height = 137 },
				textureRect = { x = 1000, y = 2, width = 167, height = 137 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_001.png",
				spriteColorRect = { x = 147, y = 121, width = 155, height = 125 },
				textureRect = { x = 1328, y = 103, width = 155, height = 125 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_003.png",
				spriteColorRect = { x = 161, y = 120, width = 141, height = 125 },
				textureRect = { x = 1867, y = 936, width = 141, height = 125 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_009.png",
				spriteColorRect = { x = 38, y = 120, width = 273, height = 125 },
				textureRect = { x = 279, y = 2, width = 273, height = 125 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_011.png",
				spriteColorRect = { x = 38, y = 122, width = 273, height = 123 },
				textureRect = { x = 2, y = 123, width = 273, height = 123 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_017.png",
				spriteColorRect = { x = 165, y = 124, width = 131, height = 121 },
				textureRect = { x = 806, y = 1376, width = 131, height = 121 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_025.png",
				spriteColorRect = { x = 145, y = 120, width = 149, height = 137 },
				textureRect = { x = 975, y = 625, width = 149, height = 137 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_033.png",
				spriteColorRect = { x = 144, y = 120, width = 153, height = 137 },
				textureRect = { x = 985, y = 256, width = 153, height = 137 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_001.png",
				spriteColorRect = { x = 147, y = 134, width = 155, height = 127 },
				textureRect = { x = 1487, y = 97, width = 155, height = 127 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_003.png",
				spriteColorRect = { x = 165, y = 138, width = 137, height = 127 },
				textureRect = { x = 951, y = 1361, width = 137, height = 127 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_009.png",
				spriteColorRect = { x = 37, y = 150, width = 275, height = 119 },
				textureRect = { x = 2, y = 2, width = 275, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_011.png",
				spriteColorRect = { x = 38, y = 149, width = 273, height = 119 },
				textureRect = { x = 554, y = 2, width = 273, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_017.png",
				spriteColorRect = { x = 155, y = 140, width = 141, height = 113 },
				textureRect = { x = 1551, y = 942, width = 141, height = 113 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_025.png",
				spriteColorRect = { x = 144, y = 134, width = 151, height = 117 },
				textureRect = { x = 1293, y = 452, width = 151, height = 117 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_033.png",
				spriteColorRect = { x = 144, y = 133, width = 153, height = 121 },
				textureRect = { x = 552, y = 414, width = 153, height = 121 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_077.png",
				spriteColorRect = { x = 161, y = 213, width = 131, height = 135 },
				textureRect = { x = 409, y = 1479, width = 131, height = 135 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_081.png",
				spriteColorRect = { x = 161, y = 213, width = 131, height = 135 },
				textureRect = { x = 411, y = 1342, width = 131, height = 135 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_085.png",
				spriteColorRect = { x = 159, y = 213, width = 133, height = 135 },
				textureRect = { x = 415, y = 1076, width = 133, height = 135 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_089.png",
				spriteColorRect = { x = 162, y = 214, width = 129, height = 133 },
				textureRect = { x = 250, y = 1726, width = 129, height = 133 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_093.png",
				spriteColorRect = { x = 162, y = 214, width = 129, height = 133 },
				textureRect = { x = 421, y = 941, width = 129, height = 133 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_097.png",
				spriteColorRect = { x = 164, y = 213, width = 127, height = 131 },
				textureRect = { x = 381, y = 1646, width = 127, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_101.png",
				spriteColorRect = { x = 163, y = 213, width = 129, height = 129 },
				textureRect = { x = 849, y = 1873, width = 129, height = 129 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_105.png",
				spriteColorRect = { x = 178, y = 213, width = 107, height = 133 },
				textureRect = { x = 375, y = 1861, width = 107, height = 133 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_109.png",
				spriteColorRect = { x = 181, y = 214, width = 103, height = 131 },
				textureRect = { x = 863, y = 1606, width = 103, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_113.png",
				spriteColorRect = { x = 180, y = 214, width = 103, height = 131 },
				textureRect = { x = 839, y = 1740, width = 103, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_117.png",
				spriteColorRect = { x = 180, y = 214, width = 103, height = 133 },
				textureRect = { x = 1942, y = 315, width = 103, height = 133 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_121.png",
				spriteColorRect = { x = 180, y = 214, width = 103, height = 131 },
				textureRect = { x = 1942, y = 450, width = 103, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_265.png",
				spriteColorRect = { x = 168, y = 214, width = 119, height = 131 },
				textureRect = { x = 728, y = 1882, width = 119, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_269.png",
				spriteColorRect = { x = 167, y = 213, width = 119, height = 131 },
				textureRect = { x = 607, y = 1882, width = 119, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_273.png",
				spriteColorRect = { x = 167, y = 213, width = 119, height = 131 },
				textureRect = { x = 633, y = 1608, width = 119, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_277.png",
				spriteColorRect = { x = 165, y = 213, width = 121, height = 131 },
				textureRect = { x = 607, y = 1749, width = 121, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_281.png",
				spriteColorRect = { x = 166, y = 213, width = 121, height = 131 },
				textureRect = { x = 510, y = 1616, width = 121, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_285.png",
				spriteColorRect = { x = 165, y = 213, width = 121, height = 131 },
				textureRect = { x = 484, y = 1912, width = 121, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_289.png",
				spriteColorRect = { x = 163, y = 213, width = 121, height = 131 },
				textureRect = { x = 484, y = 1779, width = 121, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_293.png",
				spriteColorRect = { x = 163, y = 214, width = 123, height = 129 },
				textureRect = { x = 944, y = 1739, width = 123, height = 129 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_299.png",
				spriteColorRect = { x = 160, y = 214, width = 123, height = 133 },
				textureRect = { x = 250, y = 1861, width = 123, height = 133 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_301.png",
				spriteColorRect = { x = 162, y = 214, width = 121, height = 133 },
				textureRect = { x = 429, y = 806, width = 121, height = 133 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_371.png",
				spriteColorRect = { x = 172, y = 213, width = 111, height = 129 },
				textureRect = { x = 705, y = 625, width = 111, height = 129 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_375.png",
				spriteColorRect = { x = 168, y = 213, width = 115, height = 127 },
				textureRect = { x = 435, y = 403, width = 115, height = 127 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_379.png",
				spriteColorRect = { x = 164, y = 213, width = 119, height = 125 },
				textureRect = { x = 980, y = 1870, width = 119, height = 125 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_383.png",
				spriteColorRect = { x = 172, y = 213, width = 111, height = 123 },
				textureRect = { x = 705, y = 756, width = 111, height = 123 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_387.png",
				spriteColorRect = { x = 174, y = 213, width = 109, height = 123 },
				textureRect = { x = 687, y = 1377, width = 109, height = 123 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_391.png",
				spriteColorRect = { x = 164, y = 214, width = 119, height = 127 },
				textureRect = { x = 968, y = 1606, width = 119, height = 127 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_395.png",
				spriteColorRect = { x = 170, y = 213, width = 113, height = 131 },
				textureRect = { x = 161, y = 512, width = 113, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_415.png",
				spriteColorRect = { x = 174, y = 213, width = 109, height = 131 },
				textureRect = { x = 695, y = 1244, width = 109, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_419.png",
				spriteColorRect = { x = 176, y = 213, width = 107, height = 131 },
				textureRect = { x = 754, y = 1607, width = 107, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_423.png",
				spriteColorRect = { x = 174, y = 213, width = 109, height = 131 },
				textureRect = { x = 149, y = 1462, width = 109, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_427.png",
				spriteColorRect = { x = 172, y = 214, width = 111, height = 129 },
				textureRect = { x = 714, y = 260, width = 111, height = 129 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_431.png",
				spriteColorRect = { x = 176, y = 213, width = 107, height = 131 },
				textureRect = { x = 730, y = 1741, width = 107, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_435.png",
				spriteColorRect = { x = 170, y = 213, width = 113, height = 129 },
				textureRect = { x = 709, y = 391, width = 113, height = 129 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_439.png",
				spriteColorRect = { x = 174, y = 214, width = 109, height = 129 },
				textureRect = { x = 149, y = 1595, width = 109, height = 129 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_441.png",
				spriteColorRect = { x = 172, y = 214, width = 111, height = 129 },
				textureRect = { x = 163, y = 381, width = 111, height = 129 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_445.png",
				spriteColorRect = { x = 170, y = 214, width = 113, height = 127 },
				textureRect = { x = 161, y = 645, width = 113, height = 127 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_449.png",
				spriteColorRect = { x = 174, y = 214, width = 109, height = 119 },
				textureRect = { x = 1123, y = 1408, width = 109, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_453.png",
				spriteColorRect = { x = 174, y = 213, width = 109, height = 121 },
				textureRect = { x = 1069, y = 1735, width = 109, height = 121 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_457.png",
				spriteColorRect = { x = 172, y = 213, width = 111, height = 131 },
				textureRect = { x = 163, y = 248, width = 111, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_461.png",
				spriteColorRect = { x = 174, y = 214, width = 109, height = 133 },
				textureRect = { x = 697, y = 1109, width = 109, height = 133 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_465.png",
				spriteColorRect = { x = 174, y = 213, width = 109, height = 135 },
				textureRect = { x = 717, y = 123, width = 109, height = 135 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_469.png",
				spriteColorRect = { x = 170, y = 213, width = 113, height = 135 },
				textureRect = { x = 438, y = 129, width = 113, height = 135 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_473.png",
				spriteColorRect = { x = 168, y = 213, width = 115, height = 135 },
				textureRect = { x = 435, y = 266, width = 115, height = 135 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_477.png",
				spriteColorRect = { x = 166, y = 213, width = 117, height = 135 },
				textureRect = { x = 433, y = 532, width = 117, height = 135 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_481.png",
				spriteColorRect = { x = 164, y = 213, width = 119, height = 135 },
				textureRect = { x = 129, y = 1816, width = 119, height = 135 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_485.png",
				spriteColorRect = { x = 166, y = 213, width = 119, height = 135 },
				textureRect = { x = 431, y = 669, width = 119, height = 135 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_489.png",
				spriteColorRect = { x = 164, y = 213, width = 125, height = 135 },
				textureRect = { x = 2, y = 1816, width = 125, height = 135 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_657.png",
				spriteColorRect = { x = 176, y = 214, width = 107, height = 99 },
				textureRect = { x = 1622, y = 1396, width = 107, height = 99 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_659.png",
				spriteColorRect = { x = 174, y = 214, width = 109, height = 99 },
				textureRect = { x = 1596, y = 1556, width = 109, height = 99 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_077.png",
				spriteColorRect = { x = 184, y = 207, width = 107, height = 121 },
				textureRect = { x = 1180, y = 1724, width = 107, height = 121 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_081.png",
				spriteColorRect = { x = 184, y = 206, width = 107, height = 121 },
				textureRect = { x = 1101, y = 1858, width = 107, height = 121 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_085.png",
				spriteColorRect = { x = 184, y = 206, width = 107, height = 121 },
				textureRect = { x = 1089, y = 1601, width = 107, height = 121 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_089.png",
				spriteColorRect = { x = 184, y = 209, width = 107, height = 119 },
				textureRect = { x = 1235, y = 1287, width = 107, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_093.png",
				spriteColorRect = { x = 184, y = 209, width = 107, height = 119 },
				textureRect = { x = 1234, y = 1408, width = 107, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_097.png",
				spriteColorRect = { x = 181, y = 207, width = 111, height = 123 },
				textureRect = { x = 157, y = 774, width = 111, height = 123 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_101.png",
				spriteColorRect = { x = 166, y = 212, width = 131, height = 117 },
				textureRect = { x = 542, y = 1489, width = 131, height = 117 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_105.png",
				spriteColorRect = { x = 164, y = 217, width = 127, height = 103 },
				textureRect = { x = 1420, y = 1765, width = 127, height = 103 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_109.png",
				spriteColorRect = { x = 164, y = 216, width = 127, height = 103 },
				textureRect = { x = 675, y = 1502, width = 127, height = 103 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_113.png",
				spriteColorRect = { x = 164, y = 217, width = 127, height = 101 },
				textureRect = { x = 1549, y = 1741, width = 127, height = 101 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_117.png",
				spriteColorRect = { x = 162, y = 216, width = 129, height = 101 },
				textureRect = { x = 1550, y = 1190, width = 129, height = 101 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_121.png",
				spriteColorRect = { x = 164, y = 216, width = 127, height = 101 },
				textureRect = { x = 1426, y = 1870, width = 127, height = 101 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_265.png",
				spriteColorRect = { x = 186, y = 211, width = 97, height = 115 },
				textureRect = { x = 1392, y = 1648, width = 97, height = 115 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_269.png",
				spriteColorRect = { x = 184, y = 211, width = 99, height = 115 },
				textureRect = { x = 1319, y = 1769, width = 99, height = 115 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_273.png",
				spriteColorRect = { x = 182, y = 210, width = 101, height = 115 },
				textureRect = { x = 1447, y = 1231, width = 101, height = 115 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_277.png",
				spriteColorRect = { x = 182, y = 208, width = 101, height = 117 },
				textureRect = { x = 1307, y = 1529, width = 101, height = 117 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_281.png",
				spriteColorRect = { x = 182, y = 209, width = 101, height = 117 },
				textureRect = { x = 1289, y = 1650, width = 101, height = 117 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_285.png",
				spriteColorRect = { x = 182, y = 210, width = 101, height = 115 },
				textureRect = { x = 1344, y = 1287, width = 101, height = 115 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_289.png",
				spriteColorRect = { x = 177, y = 205, width = 107, height = 119 },
				textureRect = { x = 1198, y = 1529, width = 107, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_293.png",
				spriteColorRect = { x = 174, y = 206, width = 111, height = 119 },
				textureRect = { x = 703, y = 881, width = 111, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_299.png",
				spriteColorRect = { x = 176, y = 203, width = 107, height = 117 },
				textureRect = { x = 1210, y = 1847, width = 107, height = 117 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_301.png",
				spriteColorRect = { x = 178, y = 204, width = 105, height = 115 },
				textureRect = { x = 1343, y = 1408, width = 105, height = 115 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_371.png",
				spriteColorRect = { x = 182, y = 220, width = 101, height = 95 },
				textureRect = { x = 1894, y = 1160, width = 101, height = 95 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_375.png",
				spriteColorRect = { x = 180, y = 216, width = 103, height = 99 },
				textureRect = { x = 1684, y = 1063, width = 103, height = 99 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_379.png",
				spriteColorRect = { x = 180, y = 210, width = 103, height = 105 },
				textureRect = { x = 909, y = 1499, width = 103, height = 105 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_383.png",
				spriteColorRect = { x = 180, y = 216, width = 103, height = 99 },
				textureRect = { x = 1681, y = 1190, width = 103, height = 99 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_387.png",
				spriteColorRect = { x = 180, y = 218, width = 103, height = 97 },
				textureRect = { x = 1789, y = 1063, width = 103, height = 97 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_391.png",
				spriteColorRect = { x = 180, y = 210, width = 103, height = 105 },
				textureRect = { x = 804, y = 1499, width = 103, height = 105 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_395.png",
				spriteColorRect = { x = 180, y = 218, width = 103, height = 97 },
				textureRect = { x = 1786, y = 1164, width = 103, height = 97 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_415.png",
				spriteColorRect = { x = 178, y = 218, width = 105, height = 97 },
				textureRect = { x = 1731, y = 1394, width = 105, height = 97 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_419.png",
				spriteColorRect = { x = 182, y = 216, width = 101, height = 99 },
				textureRect = { x = 1658, y = 1844, width = 101, height = 99 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_423.png",
				spriteColorRect = { x = 178, y = 218, width = 105, height = 97 },
				textureRect = { x = 1707, y = 1497, width = 105, height = 97 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_427.png",
				spriteColorRect = { x = 176, y = 220, width = 107, height = 95 },
				textureRect = { x = 1894, y = 1063, width = 107, height = 95 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_431.png",
				spriteColorRect = { x = 182, y = 216, width = 101, height = 99 },
				textureRect = { x = 1555, y = 1945, width = 101, height = 99 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_435.png",
				spriteColorRect = { x = 174, y = 218, width = 109, height = 97 },
				textureRect = { x = 1678, y = 1657, width = 109, height = 97 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_439.png",
				spriteColorRect = { x = 182, y = 216, width = 101, height = 99 },
				textureRect = { x = 1555, y = 1844, width = 101, height = 99 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_441.png",
				spriteColorRect = { x = 180, y = 218, width = 103, height = 97 },
				textureRect = { x = 1761, y = 1291, width = 103, height = 97 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_445.png",
				spriteColorRect = { x = 174, y = 218, width = 109, height = 97 },
				textureRect = { x = 1658, y = 1945, width = 109, height = 97 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_449.png",
				spriteColorRect = { x = 170, y = 214, width = 113, height = 101 },
				textureRect = { x = 707, y = 522, width = 113, height = 101 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_453.png",
				spriteColorRect = { x = 180, y = 214, width = 103, height = 101 },
				textureRect = { x = 1517, y = 1453, width = 103, height = 101 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_457.png",
				spriteColorRect = { x = 172, y = 216, width = 111, height = 99 },
				textureRect = { x = 149, y = 1361, width = 111, height = 99 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_461.png",
				spriteColorRect = { x = 180, y = 216, width = 103, height = 99 },
				textureRect = { x = 1656, y = 1293, width = 103, height = 99 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_465.png",
				spriteColorRect = { x = 180, y = 212, width = 103, height = 103 },
				textureRect = { x = 1491, y = 1636, width = 103, height = 103 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_469.png",
				spriteColorRect = { x = 178, y = 208, width = 105, height = 107 },
				textureRect = { x = 1319, y = 1886, width = 105, height = 107 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_473.png",
				spriteColorRect = { x = 178, y = 206, width = 105, height = 109 },
				textureRect = { x = 1410, y = 1525, width = 105, height = 109 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_477.png",
				spriteColorRect = { x = 177, y = 206, width = 107, height = 109 },
				textureRect = { x = 1014, y = 1490, width = 107, height = 109 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_481.png",
				spriteColorRect = { x = 178, y = 206, width = 111, height = 113 },
				textureRect = { x = 151, y = 1139, width = 111, height = 113 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_485.png",
				spriteColorRect = { x = 181, y = 207, width = 111, height = 117 },
				textureRect = { x = 153, y = 1020, width = 111, height = 117 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_489.png",
				spriteColorRect = { x = 183, y = 208, width = 111, height = 119 },
				textureRect = { x = 155, y = 899, width = 111, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_657.png",
				spriteColorRect = { x = 182, y = 214, width = 101, height = 101 },
				textureRect = { x = 1553, y = 1293, width = 101, height = 101 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_659.png",
				spriteColorRect = { x = 182, y = 212, width = 101, height = 103 },
				textureRect = { x = 1450, y = 1348, width = 101, height = 103 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_077.png",
				spriteColorRect = { x = 171, y = 225, width = 145, height = 101 },
				textureRect = { x = 2, y = 1580, width = 145, height = 101 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_081.png",
				spriteColorRect = { x = 172, y = 225, width = 147, height = 101 },
				textureRect = { x = 967, y = 881, width = 147, height = 101 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_085.png",
				spriteColorRect = { x = 172, y = 225, width = 149, height = 101 },
				textureRect = { x = 1601, y = 573, width = 149, height = 101 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_089.png",
				spriteColorRect = { x = 171, y = 225, width = 147, height = 101 },
				textureRect = { x = 2, y = 1225, width = 147, height = 101 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_093.png",
				spriteColorRect = { x = 171, y = 225, width = 149, height = 101 },
				textureRect = { x = 1126, y = 660, width = 149, height = 101 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_097.png",
				spriteColorRect = { x = 172, y = 225, width = 147, height = 103 },
				textureRect = { x = 266, y = 1065, width = 147, height = 103 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_101.png",
				spriteColorRect = { x = 172, y = 216, width = 149, height = 121 },
				textureRect = { x = 2, y = 985, width = 149, height = 121 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_105.png",
				spriteColorRect = { x = 171, y = 215, width = 143, height = 121 },
				textureRect = { x = 961, y = 1105, width = 143, height = 121 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_109.png",
				spriteColorRect = { x = 172, y = 216, width = 145, height = 119 },
				textureRect = { x = 262, y = 1392, width = 145, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_113.png",
				spriteColorRect = { x = 171, y = 218, width = 147, height = 115 },
				textureRect = { x = 552, y = 892, width = 147, height = 115 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_117.png",
				spriteColorRect = { x = 172, y = 217, width = 147, height = 115 },
				textureRect = { x = 818, y = 791, width = 147, height = 115 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_121.png",
				spriteColorRect = { x = 172, y = 217, width = 147, height = 115 },
				textureRect = { x = 969, y = 764, width = 147, height = 115 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_265.png",
				spriteColorRect = { x = 166, y = 229, width = 147, height = 87 },
				textureRect = { x = 264, y = 1170, width = 147, height = 87 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_269.png",
				spriteColorRect = { x = 166, y = 228, width = 147, height = 91 },
				textureRect = { x = 552, y = 1009, width = 147, height = 91 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_273.png",
				spriteColorRect = { x = 167, y = 227, width = 147, height = 93 },
				textureRect = { x = 816, y = 908, width = 147, height = 93 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_277.png",
				spriteColorRect = { x = 167, y = 226, width = 151, height = 95 },
				textureRect = { x = 276, y = 724, width = 151, height = 95 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_281.png",
				spriteColorRect = { x = 167, y = 224, width = 149, height = 97 },
				textureRect = { x = 1441, y = 575, width = 149, height = 97 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_285.png",
				spriteColorRect = { x = 166, y = 227, width = 151, height = 91 },
				textureRect = { x = 1288, y = 571, width = 151, height = 91 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_289.png",
				spriteColorRect = { x = 167, y = 229, width = 145, height = 93 },
				textureRect = { x = 1752, y = 573, width = 145, height = 93 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_293.png",
				spriteColorRect = { x = 167, y = 224, width = 139, height = 103 },
				textureRect = { x = 1400, y = 1126, width = 139, height = 103 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_299.png",
				spriteColorRect = { x = 166, y = 229, width = 145, height = 91 },
				textureRect = { x = 1899, y = 583, width = 145, height = 91 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_301.png",
				spriteColorRect = { x = 167, y = 232, width = 141, height = 87 },
				textureRect = { x = 1400, y = 1037, width = 141, height = 87 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_371.png",
				spriteColorRect = { x = 167, y = 220, width = 155, height = 93 },
				textureRect = { x = 828, y = 206, width = 155, height = 93 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_375.png",
				spriteColorRect = { x = 168, y = 220, width = 151, height = 93 },
				textureRect = { x = 2, y = 890, width = 151, height = 93 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_379.png",
				spriteColorRect = { x = 167, y = 218, width = 151, height = 95 },
				textureRect = { x = 552, y = 668, width = 151, height = 95 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_383.png",
				spriteColorRect = { x = 167, y = 218, width = 151, height = 95 },
				textureRect = { x = 822, y = 565, width = 151, height = 95 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_387.png",
				spriteColorRect = { x = 167, y = 218, width = 151, height = 95 },
				textureRect = { x = 977, y = 528, width = 151, height = 95 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_391.png",
				spriteColorRect = { x = 167, y = 220, width = 151, height = 93 },
				textureRect = { x = 2, y = 795, width = 151, height = 93 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_395.png",
				spriteColorRect = { x = 167, y = 220, width = 157, height = 93 },
				textureRect = { x = 1487, y = 2, width = 157, height = 93 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_415.png",
				spriteColorRect = { x = 168, y = 226, width = 155, height = 87 },
				textureRect = { x = 1326, y = 230, width = 155, height = 87 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_419.png",
				spriteColorRect = { x = 168, y = 222, width = 155, height = 91 },
				textureRect = { x = 1644, y = 222, width = 155, height = 91 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_423.png",
				spriteColorRect = { x = 168, y = 226, width = 155, height = 87 },
				textureRect = { x = 1485, y = 226, width = 155, height = 87 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_427.png",
				spriteColorRect = { x = 167, y = 228, width = 155, height = 85 },
				textureRect = { x = 1801, y = 228, width = 155, height = 85 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_431.png",
				spriteColorRect = { x = 168, y = 222, width = 155, height = 91 },
				textureRect = { x = 1803, y = 135, width = 155, height = 91 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_435.png",
				spriteColorRect = { x = 168, y = 228, width = 153, height = 85 },
				textureRect = { x = 1140, y = 256, width = 153, height = 85 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_439.png",
				spriteColorRect = { x = 168, y = 222, width = 155, height = 91 },
				textureRect = { x = 276, y = 530, width = 155, height = 91 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_441.png",
				spriteColorRect = { x = 168, y = 222, width = 155, height = 91 },
				textureRect = { x = 552, y = 321, width = 155, height = 91 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_445.png",
				spriteColorRect = { x = 168, y = 226, width = 153, height = 87 },
				textureRect = { x = 2, y = 706, width = 153, height = 87 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_449.png",
				spriteColorRect = { x = 167, y = 218, width = 149, height = 95 },
				textureRect = { x = 1428, y = 674, width = 149, height = 95 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_453.png",
				spriteColorRect = { x = 166, y = 230, width = 151, height = 83 },
				textureRect = { x = 1130, y = 575, width = 151, height = 83 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_457.png",
				spriteColorRect = { x = 166, y = 226, width = 157, height = 87 },
				textureRect = { x = 1646, y = 2, width = 157, height = 87 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_461.png",
				spriteColorRect = { x = 166, y = 222, width = 159, height = 91 },
				textureRect = { x = 2, y = 347, width = 159, height = 91 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_465.png",
				spriteColorRect = { x = 166, y = 222, width = 161, height = 91 },
				textureRect = { x = 554, y = 123, width = 161, height = 91 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_469.png",
				spriteColorRect = { x = 166, y = 224, width = 161, height = 93 },
				textureRect = { x = 829, y = 111, width = 161, height = 93 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_473.png",
				spriteColorRect = { x = 166, y = 226, width = 159, height = 97 },
				textureRect = { x = 2, y = 248, width = 159, height = 97 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_477.png",
				spriteColorRect = { x = 166, y = 229, width = 157, height = 99 },
				textureRect = { x = 1328, y = 2, width = 157, height = 99 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_481.png",
				spriteColorRect = { x = 166, y = 232, width = 153, height = 99 },
				textureRect = { x = 276, y = 623, width = 153, height = 99 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_485.png",
				spriteColorRect = { x = 167, y = 237, width = 149, height = 95 },
				textureRect = { x = 1277, y = 664, width = 149, height = 95 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_489.png",
				spriteColorRect = { x = 167, y = 235, width = 151, height = 97 },
				textureRect = { x = 1135, y = 476, width = 151, height = 97 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_657.png",
				spriteColorRect = { x = 172, y = 226, width = 119, height = 87 },
				textureRect = { x = 123, y = 1953, width = 119, height = 87 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_659.png",
				spriteColorRect = { x = 172, y = 224, width = 119, height = 89 },
				textureRect = { x = 2, y = 1953, width = 119, height = 89 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_077.png",
				spriteColorRect = { x = 170, y = 216, width = 143, height = 131 },
				textureRect = { x = 1426, y = 771, width = 143, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_081.png",
				spriteColorRect = { x = 172, y = 216, width = 141, height = 131 },
				textureRect = { x = 2, y = 1683, width = 141, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_085.png",
				spriteColorRect = { x = 172, y = 217, width = 141, height = 131 },
				textureRect = { x = 260, y = 1513, width = 141, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_089.png",
				spriteColorRect = { x = 171, y = 216, width = 141, height = 131 },
				textureRect = { x = 544, y = 1356, width = 141, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_093.png",
				spriteColorRect = { x = 172, y = 217, width = 139, height = 131 },
				textureRect = { x = 1543, y = 1057, width = 139, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_097.png",
				spriteColorRect = { x = 171, y = 217, width = 137, height = 131 },
				textureRect = { x = 1249, y = 1154, width = 137, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_101.png",
				spriteColorRect = { x = 171, y = 216, width = 143, height = 125 },
				textureRect = { x = 1112, y = 1015, width = 143, height = 125 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_105.png",
				spriteColorRect = { x = 172, y = 217, width = 147, height = 131 },
				textureRect = { x = 1277, y = 761, width = 147, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_109.png",
				spriteColorRect = { x = 172, y = 217, width = 145, height = 131 },
				textureRect = { x = 264, y = 1259, width = 145, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_113.png",
				spriteColorRect = { x = 173, y = 217, width = 143, height = 131 },
				textureRect = { x = 1579, y = 676, width = 143, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_117.png",
				spriteColorRect = { x = 173, y = 217, width = 145, height = 131 },
				textureRect = { x = 550, y = 1102, width = 145, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_121.png",
				spriteColorRect = { x = 172, y = 217, width = 143, height = 131 },
				textureRect = { x = 1897, y = 676, width = 143, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_265.png",
				spriteColorRect = { x = 167, y = 217, width = 141, height = 131 },
				textureRect = { x = 808, y = 1243, width = 141, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_269.png",
				spriteColorRect = { x = 167, y = 217, width = 141, height = 131 },
				textureRect = { x = 953, y = 1228, width = 141, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_273.png",
				spriteColorRect = { x = 167, y = 217, width = 141, height = 131 },
				textureRect = { x = 1106, y = 1142, width = 141, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_277.png",
				spriteColorRect = { x = 167, y = 217, width = 141, height = 131 },
				textureRect = { x = 1257, y = 1021, width = 141, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_281.png",
				spriteColorRect = { x = 166, y = 217, width = 141, height = 131 },
				textureRect = { x = 1408, y = 904, width = 141, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_285.png",
				spriteColorRect = { x = 167, y = 217, width = 141, height = 131 },
				textureRect = { x = 1571, y = 809, width = 141, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_289.png",
				spriteColorRect = { x = 167, y = 217, width = 141, height = 125 },
				textureRect = { x = 1867, y = 809, width = 141, height = 125 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_293.png",
				spriteColorRect = { x = 167, y = 217, width = 141, height = 123 },
				textureRect = { x = 1714, y = 938, width = 141, height = 123 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_299.png",
				spriteColorRect = { x = 167, y = 216, width = 143, height = 125 },
				textureRect = { x = 1263, y = 894, width = 143, height = 125 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_301.png",
				spriteColorRect = { x = 166, y = 217, width = 145, height = 123 },
				textureRect = { x = 1116, y = 890, width = 145, height = 123 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_371.png",
				spriteColorRect = { x = 167, y = 217, width = 151, height = 129 },
				textureRect = { x = 1636, y = 315, width = 151, height = 129 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_375.png",
				spriteColorRect = { x = 167, y = 217, width = 149, height = 127 },
				textureRect = { x = 818, y = 662, width = 149, height = 127 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_379.png",
				spriteColorRect = { x = 167, y = 216, width = 147, height = 125 },
				textureRect = { x = 1126, y = 763, width = 147, height = 125 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_383.png",
				spriteColorRect = { x = 168, y = 217, width = 145, height = 119 },
				textureRect = { x = 548, y = 1235, width = 145, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_387.png",
				spriteColorRect = { x = 168, y = 217, width = 145, height = 119 },
				textureRect = { x = 814, y = 1003, width = 145, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_391.png",
				spriteColorRect = { x = 168, y = 216, width = 149, height = 125 },
				textureRect = { x = 270, y = 821, width = 149, height = 125 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_395.png",
				spriteColorRect = { x = 168, y = 216, width = 151, height = 131 },
				textureRect = { x = 982, y = 395, width = 151, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_415.png",
				spriteColorRect = { x = 168, y = 216, width = 151, height = 127 },
				textureRect = { x = 1789, y = 444, width = 151, height = 127 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_419.png",
				spriteColorRect = { x = 168, y = 217, width = 151, height = 129 },
				textureRect = { x = 552, y = 537, width = 151, height = 129 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_423.png",
				spriteColorRect = { x = 168, y = 216, width = 151, height = 127 },
				textureRect = { x = 1789, y = 315, width = 151, height = 127 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_427.png",
				spriteColorRect = { x = 168, y = 217, width = 151, height = 125 },
				textureRect = { x = 1448, y = 448, width = 151, height = 125 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_431.png",
				spriteColorRect = { x = 168, y = 216, width = 151, height = 131 },
				textureRect = { x = 1140, y = 343, width = 151, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_435.png",
				spriteColorRect = { x = 167, y = 216, width = 151, height = 125 },
				textureRect = { x = 1636, y = 446, width = 151, height = 125 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_439.png",
				spriteColorRect = { x = 168, y = 216, width = 151, height = 131 },
				textureRect = { x = 1295, y = 319, width = 151, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_441.png",
				spriteColorRect = { x = 168, y = 216, width = 151, height = 131 },
				textureRect = { x = 1483, y = 315, width = 151, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_445.png",
				spriteColorRect = { x = 167, y = 217, width = 149, height = 125 },
				textureRect = { x = 552, y = 765, width = 149, height = 125 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_449.png",
				spriteColorRect = { x = 168, y = 217, width = 143, height = 117 },
				textureRect = { x = 808, y = 1124, width = 143, height = 117 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_453.png",
				spriteColorRect = { x = 167, y = 216, width = 145, height = 119 },
				textureRect = { x = 965, y = 984, width = 145, height = 119 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_457.png",
				spriteColorRect = { x = 167, y = 216, width = 151, height = 129 },
				textureRect = { x = 824, y = 434, width = 151, height = 129 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_461.png",
				spriteColorRect = { x = 166, y = 217, width = 155, height = 131 },
				textureRect = { x = 1805, y = 2, width = 155, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_465.png",
				spriteColorRect = { x = 166, y = 217, width = 157, height = 131 },
				textureRect = { x = 1169, y = 2, width = 157, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_469.png",
				spriteColorRect = { x = 167, y = 217, width = 157, height = 131 },
				textureRect = { x = 2, y = 573, width = 157, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_473.png",
				spriteColorRect = { x = 167, y = 217, width = 157, height = 131 },
				textureRect = { x = 2, y = 440, width = 157, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_477.png",
				spriteColorRect = { x = 167, y = 217, width = 157, height = 131 },
				textureRect = { x = 276, y = 397, width = 157, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_481.png",
				spriteColorRect = { x = 166, y = 217, width = 157, height = 131 },
				textureRect = { x = 276, y = 264, width = 157, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_485.png",
				spriteColorRect = { x = 166, y = 217, width = 155, height = 129 },
				textureRect = { x = 1646, y = 91, width = 155, height = 129 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_489.png",
				spriteColorRect = { x = 166, y = 216, width = 153, height = 131 },
				textureRect = { x = 827, y = 301, width = 153, height = 131 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_657.png",
				spriteColorRect = { x = 172, y = 217, width = 111, height = 105 },
				textureRect = { x = 151, y = 1254, width = 111, height = 105 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_659.png",
				spriteColorRect = { x = 172, y = 216, width = 111, height = 105 },
				textureRect = { x = 701, y = 1002, width = 111, height = 105 },
				spriteSourceSize = { width = 387, height = 387 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

