-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:7343f832cca9f363b8a01ce8ec69f99c$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "run-160_rgb_001.png",
				spriteColorRect = { x = 84, y = 108, width = 160, height = 118 },
				textureRect = { x = 330, y = 190, width = 160, height = 118 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_003.png",
				spriteColorRect = { x = 84, y = 114, width = 160, height = 114 },
				textureRect = { x = 164, y = 280, width = 160, height = 114 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_009.png",
				spriteColorRect = { x = 92, y = 117, width = 152, height = 114 },
				textureRect = { x = 2, y = 780, width = 152, height = 114 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_011.png",
				spriteColorRect = { x = 96, y = 117, width = 148, height = 114 },
				textureRect = { x = 1086, y = 874, width = 148, height = 114 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_017.png",
				spriteColorRect = { x = 98, y = 106, width = 152, height = 112 },
				textureRect = { x = 1120, y = 522, width = 152, height = 112 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_025.png",
				spriteColorRect = { x = 97, y = 112, width = 160, height = 102 },
				textureRect = { x = 2, y = 362, width = 160, height = 102 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_033.png",
				spriteColorRect = { x = 85, y = 112, width = 174, height = 106 },
				textureRect = { x = 2, y = 2, width = 174, height = 106 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_001.png",
				spriteColorRect = { x = 90, y = 81, width = 152, height = 134 },
				textureRect = { x = 1310, y = 510, width = 152, height = 134 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_003.png",
				spriteColorRect = { x = 92, y = 80, width = 150, height = 134 },
				textureRect = { x = 312, y = 752, width = 150, height = 134 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_009.png",
				spriteColorRect = { x = 100, y = 82, width = 142, height = 132 },
				textureRect = { x = 1346, y = 1178, width = 142, height = 132 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_011.png",
				spriteColorRect = { x = 102, y = 84, width = 140, height = 130 },
				textureRect = { x = 1186, y = 1188, width = 140, height = 130 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_017.png",
				spriteColorRect = { x = 107, y = 88, width = 136, height = 126 },
				textureRect = { x = 586, y = 1192, width = 136, height = 126 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_025.png",
				spriteColorRect = { x = 104, y = 84, width = 158, height = 132 },
				textureRect = { x = 1008, y = 96, width = 158, height = 132 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_033.png",
				spriteColorRect = { x = 93, y = 80, width = 170, height = 136 },
				textureRect = { x = 178, y = 2, width = 170, height = 136 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_001.png",
				spriteColorRect = { x = 112, y = 89, width = 158, height = 126 },
				textureRect = { x = 846, y = 104, width = 158, height = 126 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_003.png",
				spriteColorRect = { x = 126, y = 90, width = 144, height = 124 },
				textureRect = { x = 1530, y = 1082, width = 144, height = 124 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_009.png",
				spriteColorRect = { x = 127, y = 90, width = 152, height = 124 },
				textureRect = { x = 800, y = 476, width = 152, height = 124 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_011.png",
				spriteColorRect = { x = 127, y = 90, width = 152, height = 124 },
				textureRect = { x = 966, y = 474, width = 152, height = 124 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_017.png",
				spriteColorRect = { x = 123, y = 94, width = 142, height = 120 },
				textureRect = { x = 148, y = 1078, width = 142, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_025.png",
				spriteColorRect = { x = 106, y = 89, width = 156, height = 136 },
				textureRect = { x = 1812, y = 178, width = 156, height = 136 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_033.png",
				spriteColorRect = { x = 105, y = 88, width = 160, height = 138 },
				textureRect = { x = 168, y = 140, width = 160, height = 138 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_001.png",
				spriteColorRect = { x = 110, y = 102, width = 160, height = 128 },
				textureRect = { x = 2, y = 232, width = 160, height = 128 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_003.png",
				spriteColorRect = { x = 126, y = 108, width = 144, height = 126 },
				textureRect = { x = 1384, y = 1050, width = 144, height = 126 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_009.png",
				spriteColorRect = { x = 128, y = 118, width = 152, height = 120 },
				textureRect = { x = 158, y = 712, width = 152, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_011.png",
				spriteColorRect = { x = 126, y = 119, width = 154, height = 118 },
				textureRect = { x = 644, y = 364, width = 154, height = 118 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_017.png",
				spriteColorRect = { x = 118, y = 110, width = 146, height = 112 },
				textureRect = { x = 1534, y = 968, width = 146, height = 112 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_025.png",
				spriteColorRect = { x = 101, y = 104, width = 162, height = 116 },
				textureRect = { x = 682, y = 2, width = 162, height = 116 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_033.png",
				spriteColorRect = { x = 101, y = 103, width = 164, height = 120 },
				textureRect = { x = 2, y = 110, width = 164, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_077.png",
				spriteColorRect = { x = 92, y = 183, width = 142, height = 122 },
				textureRect = { x = 898, y = 1048, width = 142, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_081.png",
				spriteColorRect = { x = 90, y = 183, width = 144, height = 122 },
				textureRect = { x = 1676, y = 1084, width = 144, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_085.png",
				spriteColorRect = { x = 90, y = 183, width = 144, height = 122 },
				textureRect = { x = 1834, y = 1026, width = 144, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_089.png",
				spriteColorRect = { x = 92, y = 183, width = 142, height = 122 },
				textureRect = { x = 754, y = 944, width = 142, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_093.png",
				spriteColorRect = { x = 91, y = 183, width = 142, height = 122 },
				textureRect = { x = 610, y = 944, width = 142, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_097.png",
				spriteColorRect = { x = 95, y = 183, width = 136, height = 122 },
				textureRect = { x = 432, y = 1218, width = 136, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_101.png",
				spriteColorRect = { x = 94, y = 183, width = 140, height = 122 },
				textureRect = { x = 598, y = 1068, width = 140, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_105.png",
				spriteColorRect = { x = 109, y = 183, width = 118, height = 122 },
				textureRect = { x = 1080, y = 1546, width = 118, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_109.png",
				spriteColorRect = { x = 111, y = 183, width = 114, height = 122 },
				textureRect = { x = 720, y = 1918, width = 114, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_113.png",
				spriteColorRect = { x = 111, y = 183, width = 114, height = 122 },
				textureRect = { x = 614, y = 1794, width = 114, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_117.png",
				spriteColorRect = { x = 109, y = 183, width = 116, height = 122 },
				textureRect = { x = 496, y = 1812, width = 116, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_121.png",
				spriteColorRect = { x = 109, y = 183, width = 116, height = 122 },
				textureRect = { x = 378, y = 1812, width = 116, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_265.png",
				spriteColorRect = { x = 97, y = 183, width = 128, height = 122 },
				textureRect = { x = 266, y = 1502, width = 128, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_269.png",
				spriteColorRect = { x = 97, y = 183, width = 128, height = 122 },
				textureRect = { x = 408, y = 1466, width = 128, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_273.png",
				spriteColorRect = { x = 97, y = 183, width = 128, height = 122 },
				textureRect = { x = 554, y = 1444, width = 128, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_277.png",
				spriteColorRect = { x = 97, y = 183, width = 128, height = 122 },
				textureRect = { x = 702, y = 1398, width = 128, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_281.png",
				spriteColorRect = { x = 98, y = 183, width = 128, height = 122 },
				textureRect = { x = 856, y = 1296, width = 128, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_285.png",
				spriteColorRect = { x = 96, y = 183, width = 132, height = 122 },
				textureRect = { x = 880, y = 1172, width = 132, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_289.png",
				spriteColorRect = { x = 93, y = 183, width = 132, height = 122 },
				textureRect = { x = 2, y = 1364, width = 132, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_293.png",
				spriteColorRect = { x = 95, y = 183, width = 130, height = 122 },
				textureRect = { x = 276, y = 1378, width = 130, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_299.png",
				spriteColorRect = { x = 93, y = 183, width = 132, height = 122 },
				textureRect = { x = 142, y = 1306, width = 132, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_301.png",
				spriteColorRect = { x = 95, y = 183, width = 130, height = 122 },
				textureRect = { x = 422, y = 1342, width = 130, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_371.png",
				spriteColorRect = { x = 99, y = 183, width = 126, height = 122 },
				textureRect = { x = 1328, y = 1312, width = 126, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_375.png",
				spriteColorRect = { x = 97, y = 183, width = 128, height = 122 },
				textureRect = { x = 1014, y = 1218, width = 128, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_379.png",
				spriteColorRect = { x = 95, y = 183, width = 130, height = 122 },
				textureRect = { x = 570, y = 1320, width = 130, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_383.png",
				spriteColorRect = { x = 103, y = 182, width = 122, height = 122 },
				textureRect = { x = 254, y = 1902, width = 122, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_387.png",
				spriteColorRect = { x = 103, y = 183, width = 122, height = 122 },
				textureRect = { x = 254, y = 1778, width = 122, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_391.png",
				spriteColorRect = { x = 95, y = 183, width = 130, height = 122 },
				textureRect = { x = 724, y = 1274, width = 130, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_395.png",
				spriteColorRect = { x = 97, y = 183, width = 128, height = 122 },
				textureRect = { x = 2, y = 1488, width = 128, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_415.png",
				spriteColorRect = { x = 101, y = 183, width = 124, height = 122 },
				textureRect = { x = 538, y = 1568, width = 124, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_419.png",
				spriteColorRect = { x = 103, y = 183, width = 122, height = 122 },
				textureRect = { x = 130, y = 1902, width = 122, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_423.png",
				spriteColorRect = { x = 101, y = 183, width = 124, height = 122 },
				textureRect = { x = 684, y = 1522, width = 124, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_427.png",
				spriteColorRect = { x = 99, y = 183, width = 126, height = 122 },
				textureRect = { x = 1490, y = 1208, width = 126, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_431.png",
				spriteColorRect = { x = 103, y = 183, width = 122, height = 122 },
				textureRect = { x = 130, y = 1778, width = 122, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_435.png",
				spriteColorRect = { x = 97, y = 183, width = 128, height = 122 },
				textureRect = { x = 136, y = 1430, width = 128, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_439.png",
				spriteColorRect = { x = 101, y = 183, width = 124, height = 122 },
				textureRect = { x = 832, y = 1420, width = 124, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_441.png",
				spriteColorRect = { x = 99, y = 183, width = 126, height = 122 },
				textureRect = { x = 2, y = 1860, width = 126, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_445.png",
				spriteColorRect = { x = 99, y = 183, width = 126, height = 122 },
				textureRect = { x = 2, y = 1736, width = 126, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_449.png",
				spriteColorRect = { x = 101, y = 182, width = 124, height = 120 },
				textureRect = { x = 396, y = 1590, width = 124, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_453.png",
				spriteColorRect = { x = 103, y = 183, width = 122, height = 120 },
				textureRect = { x = 1742, y = 1272, width = 122, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_457.png",
				spriteColorRect = { x = 99, y = 183, width = 126, height = 122 },
				textureRect = { x = 2, y = 1612, width = 126, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_461.png",
				spriteColorRect = { x = 99, y = 183, width = 126, height = 122 },
				textureRect = { x = 132, y = 1554, width = 126, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_465.png",
				spriteColorRect = { x = 103, y = 183, width = 122, height = 122 },
				textureRect = { x = 1618, y = 1208, width = 122, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_469.png",
				spriteColorRect = { x = 105, y = 183, width = 120, height = 122 },
				textureRect = { x = 1580, y = 1420, width = 120, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_473.png",
				spriteColorRect = { x = 105, y = 183, width = 120, height = 122 },
				textureRect = { x = 1704, y = 1394, width = 120, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_477.png",
				spriteColorRect = { x = 101, y = 183, width = 124, height = 122 },
				textureRect = { x = 986, y = 1342, width = 124, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_481.png",
				spriteColorRect = { x = 99, y = 183, width = 126, height = 122 },
				textureRect = { x = 1920, y = 534, width = 126, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_485.png",
				spriteColorRect = { x = 97, y = 183, width = 130, height = 122 },
				textureRect = { x = 1916, y = 658, width = 130, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_489.png",
				spriteColorRect = { x = 97, y = 183, width = 134, height = 122 },
				textureRect = { x = 286, y = 1254, width = 134, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_657.png",
				spriteColorRect = { x = 117, y = 182, width = 108, height = 100 },
				textureRect = { x = 1636, y = 1750, width = 108, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_659.png",
				spriteColorRect = { x = 117, y = 183, width = 108, height = 98 },
				textureRect = { x = 1746, y = 1718, width = 108, height = 98 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_077.png",
				spriteColorRect = { x = 122, y = 177, width = 110, height = 120 },
				textureRect = { x = 1068, y = 1794, width = 110, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_081.png",
				spriteColorRect = { x = 122, y = 176, width = 110, height = 120 },
				textureRect = { x = 964, y = 1672, width = 110, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_085.png",
				spriteColorRect = { x = 120, y = 176, width = 112, height = 120 },
				textureRect = { x = 954, y = 1866, width = 112, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_089.png",
				spriteColorRect = { x = 118, y = 177, width = 114, height = 120 },
				textureRect = { x = 848, y = 1744, width = 114, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_093.png",
				spriteColorRect = { x = 117, y = 177, width = 116, height = 120 },
				textureRect = { x = 836, y = 1870, width = 116, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_097.png",
				spriteColorRect = { x = 110, y = 176, width = 124, height = 122 },
				textureRect = { x = 1144, y = 1320, width = 124, height = 122 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_101.png",
				spriteColorRect = { x = 97, y = 180, width = 142, height = 118 },
				textureRect = { x = 2, y = 1140, width = 142, height = 118 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_105.png",
				spriteColorRect = { x = 95, y = 185, width = 138, height = 104 },
				textureRect = { x = 146, y = 1200, width = 138, height = 104 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_109.png",
				spriteColorRect = { x = 95, y = 185, width = 138, height = 102 },
				textureRect = { x = 740, y = 1068, width = 138, height = 102 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_113.png",
				spriteColorRect = { x = 95, y = 185, width = 138, height = 102 },
				textureRect = { x = 2, y = 1260, width = 138, height = 102 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_117.png",
				spriteColorRect = { x = 93, y = 186, width = 140, height = 100 },
				textureRect = { x = 444, y = 1116, width = 140, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_121.png",
				spriteColorRect = { x = 95, y = 186, width = 138, height = 100 },
				textureRect = { x = 740, y = 1172, width = 138, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_265.png",
				spriteColorRect = { x = 111, y = 181, width = 114, height = 114 },
				textureRect = { x = 1412, y = 1782, width = 114, height = 114 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_269.png",
				spriteColorRect = { x = 111, y = 179, width = 114, height = 116 },
				textureRect = { x = 1186, y = 1908, width = 114, height = 116 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_273.png",
				spriteColorRect = { x = 109, y = 178, width = 116, height = 116 },
				textureRect = { x = 1190, y = 1670, width = 116, height = 116 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_277.png",
				spriteColorRect = { x = 109, y = 178, width = 116, height = 116 },
				textureRect = { x = 1180, y = 1790, width = 116, height = 116 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_281.png",
				spriteColorRect = { x = 109, y = 179, width = 116, height = 116 },
				textureRect = { x = 1068, y = 1916, width = 116, height = 116 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_285.png",
				spriteColorRect = { x = 109, y = 179, width = 116, height = 114 },
				textureRect = { x = 1302, y = 1906, width = 116, height = 114 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_289.png",
				spriteColorRect = { x = 113, y = 175, width = 112, height = 118 },
				textureRect = { x = 1076, y = 1670, width = 112, height = 118 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_293.png",
				spriteColorRect = { x = 111, y = 174, width = 116, height = 120 },
				textureRect = { x = 730, y = 1748, width = 116, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_299.png",
				spriteColorRect = { x = 113, y = 173, width = 112, height = 116 },
				textureRect = { x = 1298, y = 1788, width = 112, height = 116 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_301.png",
				spriteColorRect = { x = 113, y = 174, width = 112, height = 114 },
				textureRect = { x = 1426, y = 1666, width = 112, height = 114 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_371.png",
				spriteColorRect = { x = 107, y = 188, width = 118, height = 96 },
				textureRect = { x = 1822, y = 1568, width = 118, height = 96 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_375.png",
				spriteColorRect = { x = 107, y = 184, width = 118, height = 100 },
				textureRect = { x = 522, y = 1692, width = 118, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_379.png",
				spriteColorRect = { x = 109, y = 180, width = 116, height = 104 },
				textureRect = { x = 1434, y = 1544, width = 116, height = 104 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_383.png",
				spriteColorRect = { x = 109, y = 184, width = 116, height = 100 },
				textureRect = { x = 1552, y = 1648, width = 116, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_387.png",
				spriteColorRect = { x = 109, y = 186, width = 116, height = 98 },
				textureRect = { x = 1644, y = 1852, width = 116, height = 98 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_391.png",
				spriteColorRect = { x = 107, y = 178, width = 118, height = 106 },
				textureRect = { x = 932, y = 1564, width = 118, height = 106 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_395.png",
				spriteColorRect = { x = 107, y = 188, width = 118, height = 96 },
				textureRect = { x = 1702, y = 1518, width = 118, height = 96 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_415.png",
				spriteColorRect = { x = 105, y = 188, width = 120, height = 96 },
				textureRect = { x = 810, y = 1544, width = 120, height = 96 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_419.png",
				spriteColorRect = { x = 109, y = 184, width = 116, height = 100 },
				textureRect = { x = 1670, y = 1616, width = 116, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_423.png",
				spriteColorRect = { x = 105, y = 188, width = 120, height = 96 },
				textureRect = { x = 958, y = 1466, width = 120, height = 96 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_427.png",
				spriteColorRect = { x = 103, y = 188, width = 122, height = 96 },
				textureRect = { x = 1866, y = 1370, width = 122, height = 96 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_431.png",
				spriteColorRect = { x = 107, y = 184, width = 118, height = 100 },
				textureRect = { x = 664, y = 1646, width = 118, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_435.png",
				spriteColorRect = { x = 103, y = 188, width = 122, height = 96 },
				textureRect = { x = 1866, y = 1272, width = 122, height = 96 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_439.png",
				spriteColorRect = { x = 107, y = 186, width = 118, height = 98 },
				textureRect = { x = 1826, y = 1468, width = 118, height = 98 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_441.png",
				spriteColorRect = { x = 107, y = 186, width = 118, height = 98 },
				textureRect = { x = 386, y = 1712, width = 118, height = 98 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_445.png",
				spriteColorRect = { x = 101, y = 186, width = 124, height = 98 },
				textureRect = { x = 130, y = 1678, width = 124, height = 98 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_449.png",
				spriteColorRect = { x = 105, y = 184, width = 120, height = 100 },
				textureRect = { x = 1112, y = 1444, width = 120, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_453.png",
				spriteColorRect = { x = 109, y = 182, width = 116, height = 102 },
				textureRect = { x = 1552, y = 1544, width = 116, height = 102 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_457.png",
				spriteColorRect = { x = 101, y = 186, width = 124, height = 98 },
				textureRect = { x = 260, y = 1626, width = 124, height = 98 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_461.png",
				spriteColorRect = { x = 107, y = 184, width = 118, height = 100 },
				textureRect = { x = 810, y = 1642, width = 118, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_465.png",
				spriteColorRect = { x = 109, y = 180, width = 116, height = 104 },
				textureRect = { x = 1316, y = 1556, width = 116, height = 104 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_469.png",
				spriteColorRect = { x = 111, y = 178, width = 114, height = 106 },
				textureRect = { x = 1200, y = 1556, width = 114, height = 106 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_473.png",
				spriteColorRect = { x = 113, y = 176, width = 112, height = 108 },
				textureRect = { x = 490, y = 1936, width = 112, height = 108 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_477.png",
				spriteColorRect = { x = 115, y = 174, width = 110, height = 110 },
				textureRect = { x = 378, y = 1936, width = 110, height = 110 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_481.png",
				spriteColorRect = { x = 115, y = 174, width = 116, height = 114 },
				textureRect = { x = 1308, y = 1666, width = 116, height = 114 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_485.png",
				spriteColorRect = { x = 115, y = 175, width = 120, height = 118 },
				textureRect = { x = 1270, y = 1436, width = 120, height = 118 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_489.png",
				spriteColorRect = { x = 116, y = 176, width = 120, height = 120 },
				textureRect = { x = 1456, y = 1422, width = 120, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_657.png",
				spriteColorRect = { x = 119, y = 182, width = 106, height = 102 },
				textureRect = { x = 1536, y = 1888, width = 106, height = 102 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_659.png",
				spriteColorRect = { x = 119, y = 180, width = 106, height = 104 },
				textureRect = { x = 1528, y = 1782, width = 106, height = 104 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_077.png",
				spriteColorRect = { x = 108, y = 195, width = 150, height = 100 },
				textureRect = { x = 1616, y = 520, width = 150, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_081.png",
				spriteColorRect = { x = 110, y = 195, width = 150, height = 100 },
				textureRect = { x = 1464, y = 520, width = 150, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_085.png",
				spriteColorRect = { x = 109, y = 195, width = 154, height = 100 },
				textureRect = { x = 482, y = 436, width = 154, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_089.png",
				spriteColorRect = { x = 111, y = 195, width = 148, height = 100 },
				textureRect = { x = 1560, y = 744, width = 148, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_093.png",
				spriteColorRect = { x = 110, y = 195, width = 152, height = 100 },
				textureRect = { x = 954, y = 600, width = 152, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_097.png",
				spriteColorRect = { x = 110, y = 195, width = 150, height = 102 },
				textureRect = { x = 936, y = 702, width = 150, height = 102 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_101.png",
				spriteColorRect = { x = 111, y = 185, width = 152, height = 120 },
				textureRect = { x = 314, y = 630, width = 152, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_105.png",
				spriteColorRect = { x = 111, y = 184, width = 146, height = 120 },
				textureRect = { x = 1686, y = 962, width = 146, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_109.png",
				spriteColorRect = { x = 111, y = 186, width = 148, height = 118 },
				textureRect = { x = 1410, y = 714, width = 148, height = 118 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_113.png",
				spriteColorRect = { x = 111, y = 186, width = 148, height = 116 },
				textureRect = { x = 1238, y = 766, width = 148, height = 116 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_117.png",
				spriteColorRect = { x = 110, y = 185, width = 150, height = 116 },
				textureRect = { x = 1108, y = 636, width = 150, height = 116 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_121.png",
				spriteColorRect = { x = 111, y = 185, width = 150, height = 116 },
				textureRect = { x = 464, y = 754, width = 150, height = 116 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_265.png",
				spriteColorRect = { x = 106, y = 199, width = 148, height = 86 },
				textureRect = { x = 1710, y = 752, width = 148, height = 86 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_269.png",
				spriteColorRect = { x = 105, y = 197, width = 150, height = 90 },
				textureRect = { x = 1464, y = 622, width = 150, height = 90 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_273.png",
				spriteColorRect = { x = 106, y = 195, width = 150, height = 94 },
				textureRect = { x = 1768, y = 534, width = 150, height = 94 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_277.png",
				spriteColorRect = { x = 106, y = 194, width = 154, height = 96 },
				textureRect = { x = 2, y = 682, width = 154, height = 96 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_281.png",
				spriteColorRect = { x = 106, y = 194, width = 152, height = 96 },
				textureRect = { x = 792, y = 602, width = 152, height = 96 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_285.png",
				spriteColorRect = { x = 106, y = 195, width = 152, height = 92 },
				textureRect = { x = 468, y = 660, width = 152, height = 92 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_289.png",
				spriteColorRect = { x = 106, y = 199, width = 148, height = 92 },
				textureRect = { x = 1388, y = 834, width = 148, height = 92 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_293.png",
				spriteColorRect = { x = 106, y = 192, width = 142, height = 104 },
				textureRect = { x = 1042, y = 1112, width = 142, height = 104 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_299.png",
				spriteColorRect = { x = 105, y = 199, width = 148, height = 90 },
				textureRect = { x = 1236, y = 884, width = 148, height = 90 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_301.png",
				spriteColorRect = { x = 106, y = 200, width = 144, height = 88 },
				textureRect = { x = 1200, y = 1098, width = 144, height = 88 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_371.png",
				spriteColorRect = { x = 106, y = 189, width = 158, height = 92 },
				textureRect = { x = 2, y = 466, width = 158, height = 92 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_375.png",
				spriteColorRect = { x = 105, y = 187, width = 156, height = 94 },
				textureRect = { x = 162, y = 518, width = 156, height = 94 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_379.png",
				spriteColorRect = { x = 105, y = 187, width = 154, height = 94 },
				textureRect = { x = 1154, y = 426, width = 154, height = 94 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_383.png",
				spriteColorRect = { x = 105, y = 187, width = 154, height = 94 },
				textureRect = { x = 1788, y = 438, width = 154, height = 94 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_387.png",
				spriteColorRect = { x = 105, y = 187, width = 154, height = 94 },
				textureRect = { x = 1632, y = 424, width = 154, height = 94 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_391.png",
				spriteColorRect = { x = 106, y = 187, width = 154, height = 94 },
				textureRect = { x = 1476, y = 424, width = 154, height = 94 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_395.png",
				spriteColorRect = { x = 105, y = 189, width = 160, height = 92 },
				textureRect = { x = 1008, y = 2, width = 160, height = 92 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_415.png",
				spriteColorRect = { x = 105, y = 195, width = 160, height = 86 },
				textureRect = { x = 1170, y = 94, width = 160, height = 86 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_419.png",
				spriteColorRect = { x = 105, y = 191, width = 160, height = 90 },
				textureRect = { x = 1656, y = 2, width = 160, height = 90 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_423.png",
				spriteColorRect = { x = 105, y = 195, width = 160, height = 86 },
				textureRect = { x = 1818, y = 90, width = 160, height = 86 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_427.png",
				spriteColorRect = { x = 106, y = 197, width = 158, height = 84 },
				textureRect = { x = 1652, y = 94, width = 158, height = 84 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_431.png",
				spriteColorRect = { x = 105, y = 191, width = 160, height = 90 },
				textureRect = { x = 1494, y = 2, width = 160, height = 90 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_435.png",
				spriteColorRect = { x = 105, y = 197, width = 158, height = 84 },
				textureRect = { x = 1492, y = 94, width = 158, height = 84 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_439.png",
				spriteColorRect = { x = 105, y = 191, width = 160, height = 90 },
				textureRect = { x = 1332, y = 2, width = 160, height = 90 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_441.png",
				spriteColorRect = { x = 105, y = 191, width = 160, height = 90 },
				textureRect = { x = 1170, y = 2, width = 160, height = 90 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_445.png",
				spriteColorRect = { x = 105, y = 195, width = 158, height = 86 },
				textureRect = { x = 1332, y = 94, width = 158, height = 86 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_449.png",
				spriteColorRect = { x = 106, y = 187, width = 152, height = 94 },
				textureRect = { x = 630, y = 606, width = 152, height = 94 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_453.png",
				spriteColorRect = { x = 105, y = 199, width = 154, height = 82 },
				textureRect = { x = 1310, y = 426, width = 154, height = 82 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_457.png",
				spriteColorRect = { x = 105, y = 195, width = 160, height = 86 },
				textureRect = { x = 1818, y = 2, width = 160, height = 86 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_461.png",
				spriteColorRect = { x = 105, y = 191, width = 162, height = 90 },
				textureRect = { x = 350, y = 98, width = 162, height = 90 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_465.png",
				spriteColorRect = { x = 105, y = 191, width = 164, height = 90 },
				textureRect = { x = 516, y = 2, width = 164, height = 90 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_469.png",
				spriteColorRect = { x = 105, y = 192, width = 164, height = 94 },
				textureRect = { x = 350, y = 2, width = 164, height = 94 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_473.png",
				spriteColorRect = { x = 105, y = 196, width = 162, height = 96 },
				textureRect = { x = 516, y = 94, width = 162, height = 96 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_477.png",
				spriteColorRect = { x = 105, y = 197, width = 160, height = 100 },
				textureRect = { x = 846, y = 2, width = 160, height = 100 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_481.png",
				spriteColorRect = { x = 105, y = 201, width = 156, height = 98 },
				textureRect = { x = 324, y = 432, width = 156, height = 98 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_485.png",
				spriteColorRect = { x = 105, y = 205, width = 154, height = 96 },
				textureRect = { x = 158, y = 614, width = 154, height = 96 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_489.png",
				spriteColorRect = { x = 105, y = 205, width = 154, height = 96 },
				textureRect = { x = 320, y = 532, width = 154, height = 96 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_657.png",
				spriteColorRect = { x = 111, y = 195, width = 122, height = 86 },
				textureRect = { x = 1580, y = 1332, width = 122, height = 86 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_659.png",
				spriteColorRect = { x = 111, y = 193, width = 122, height = 88 },
				textureRect = { x = 1456, y = 1332, width = 122, height = 88 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_077.png",
				spriteColorRect = { x = 109, y = 185, width = 146, height = 120 },
				textureRect = { x = 1858, y = 904, width = 146, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_081.png",
				spriteColorRect = { x = 109, y = 185, width = 146, height = 120 },
				textureRect = { x = 1236, y = 976, width = 146, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_085.png",
				spriteColorRect = { x = 110, y = 185, width = 144, height = 120 },
				textureRect = { x = 1054, y = 990, width = 144, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_089.png",
				spriteColorRect = { x = 111, y = 185, width = 142, height = 120 },
				textureRect = { x = 300, y = 1010, width = 142, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_093.png",
				spriteColorRect = { x = 111, y = 185, width = 142, height = 120 },
				textureRect = { x = 454, y = 994, width = 142, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_097.png",
				spriteColorRect = { x = 111, y = 185, width = 138, height = 120 },
				textureRect = { x = 292, y = 1132, width = 138, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_101.png",
				spriteColorRect = { x = 110, y = 185, width = 146, height = 120 },
				textureRect = { x = 1386, y = 928, width = 146, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_105.png",
				spriteColorRect = { x = 111, y = 185, width = 150, height = 120 },
				textureRect = { x = 784, y = 700, width = 150, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_109.png",
				spriteColorRect = { x = 110, y = 185, width = 148, height = 120 },
				textureRect = { x = 1766, y = 630, width = 148, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_113.png",
				spriteColorRect = { x = 111, y = 185, width = 146, height = 120 },
				textureRect = { x = 1538, y = 846, width = 146, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_117.png",
				spriteColorRect = { x = 110, y = 185, width = 150, height = 120 },
				textureRect = { x = 2, y = 896, width = 150, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_121.png",
				spriteColorRect = { x = 111, y = 185, width = 146, height = 120 },
				textureRect = { x = 1710, y = 840, width = 146, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_265.png",
				spriteColorRect = { x = 105, y = 185, width = 144, height = 120 },
				textureRect = { x = 908, y = 926, width = 144, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_269.png",
				spriteColorRect = { x = 105, y = 185, width = 144, height = 120 },
				textureRect = { x = 762, y = 822, width = 144, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_273.png",
				spriteColorRect = { x = 105, y = 185, width = 144, height = 120 },
				textureRect = { x = 2, y = 1018, width = 144, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_277.png",
				spriteColorRect = { x = 105, y = 185, width = 144, height = 120 },
				textureRect = { x = 154, y = 956, width = 144, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_281.png",
				spriteColorRect = { x = 105, y = 185, width = 144, height = 120 },
				textureRect = { x = 308, y = 888, width = 144, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_285.png",
				spriteColorRect = { x = 105, y = 185, width = 144, height = 120 },
				textureRect = { x = 464, y = 872, width = 144, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_289.png",
				spriteColorRect = { x = 105, y = 185, width = 144, height = 120 },
				textureRect = { x = 616, y = 822, width = 144, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_293.png",
				spriteColorRect = { x = 105, y = 185, width = 144, height = 120 },
				textureRect = { x = 1822, y = 1150, width = 144, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_299.png",
				spriteColorRect = { x = 106, y = 185, width = 146, height = 120 },
				textureRect = { x = 1860, y = 782, width = 146, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_301.png",
				spriteColorRect = { x = 105, y = 185, width = 148, height = 120 },
				textureRect = { x = 1616, y = 622, width = 148, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_371.png",
				spriteColorRect = { x = 105, y = 185, width = 154, height = 120 },
				textureRect = { x = 810, y = 354, width = 154, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_375.png",
				spriteColorRect = { x = 106, y = 185, width = 152, height = 120 },
				textureRect = { x = 476, y = 538, width = 152, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_379.png",
				spriteColorRect = { x = 106, y = 185, width = 150, height = 120 },
				textureRect = { x = 156, y = 834, width = 150, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_383.png",
				spriteColorRect = { x = 106, y = 186, width = 148, height = 118 },
				textureRect = { x = 936, y = 806, width = 148, height = 118 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_387.png",
				spriteColorRect = { x = 105, y = 186, width = 150, height = 118 },
				textureRect = { x = 622, y = 702, width = 150, height = 118 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_391.png",
				spriteColorRect = { x = 105, y = 185, width = 154, height = 120 },
				textureRect = { x = 998, y = 352, width = 154, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_395.png",
				spriteColorRect = { x = 105, y = 185, width = 156, height = 120 },
				textureRect = { x = 486, y = 314, width = 156, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_415.png",
				spriteColorRect = { x = 105, y = 185, width = 156, height = 120 },
				textureRect = { x = 652, y = 242, width = 156, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_419.png",
				spriteColorRect = { x = 105, y = 185, width = 156, height = 120 },
				textureRect = { x = 1326, y = 182, width = 156, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_423.png",
				spriteColorRect = { x = 105, y = 185, width = 156, height = 120 },
				textureRect = { x = 840, y = 232, width = 156, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_427.png",
				spriteColorRect = { x = 106, y = 185, width = 154, height = 120 },
				textureRect = { x = 1320, y = 304, width = 154, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_431.png",
				spriteColorRect = { x = 106, y = 185, width = 154, height = 120 },
				textureRect = { x = 1164, y = 304, width = 154, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_435.png",
				spriteColorRect = { x = 105, y = 185, width = 154, height = 120 },
				textureRect = { x = 1796, y = 316, width = 154, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_439.png",
				spriteColorRect = { x = 106, y = 185, width = 154, height = 120 },
				textureRect = { x = 1640, y = 302, width = 154, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_441.png",
				spriteColorRect = { x = 106, y = 185, width = 154, height = 120 },
				textureRect = { x = 1484, y = 302, width = 154, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_445.png",
				spriteColorRect = { x = 106, y = 185, width = 152, height = 120 },
				textureRect = { x = 638, y = 484, width = 152, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_449.png",
				spriteColorRect = { x = 105, y = 185, width = 148, height = 118 },
				textureRect = { x = 1088, y = 754, width = 148, height = 118 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_453.png",
				spriteColorRect = { x = 105, y = 186, width = 148, height = 118 },
				textureRect = { x = 1260, y = 646, width = 148, height = 118 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_457.png",
				spriteColorRect = { x = 105, y = 185, width = 154, height = 120 },
				textureRect = { x = 2, y = 560, width = 154, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_461.png",
				spriteColorRect = { x = 105, y = 185, width = 158, height = 120 },
				textureRect = { x = 164, y = 396, width = 158, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_465.png",
				spriteColorRect = { x = 105, y = 185, width = 158, height = 120 },
				textureRect = { x = 326, y = 310, width = 158, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_469.png",
				spriteColorRect = { x = 105, y = 185, width = 156, height = 120 },
				textureRect = { x = 1006, y = 230, width = 156, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_473.png",
				spriteColorRect = { x = 105, y = 185, width = 156, height = 120 },
				textureRect = { x = 1168, y = 182, width = 156, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_477.png",
				spriteColorRect = { x = 106, y = 185, width = 156, height = 120 },
				textureRect = { x = 1650, y = 180, width = 156, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_481.png",
				spriteColorRect = { x = 105, y = 185, width = 158, height = 120 },
				textureRect = { x = 492, y = 192, width = 158, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_485.png",
				spriteColorRect = { x = 105, y = 185, width = 158, height = 120 },
				textureRect = { x = 680, y = 120, width = 158, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_489.png",
				spriteColorRect = { x = 105, y = 185, width = 156, height = 120 },
				textureRect = { x = 1492, y = 180, width = 156, height = 120 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_657.png",
				spriteColorRect = { x = 111, y = 185, width = 114, height = 106 },
				textureRect = { x = 604, y = 1936, width = 114, height = 106 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_659.png",
				spriteColorRect = { x = 111, y = 186, width = 114, height = 104 },
				textureRect = { x = 1420, y = 1898, width = 114, height = 104 },
				spriteSourceSize = { width = 326, height = 326 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

