-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:600ffd6d7ccfa7503cc212f9828835ef$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "run-0_rgb_001.png",
				spriteColorRect = { x = 124, y = 88, width = 103, height = 179 },
				textureRect = { x = 373, y = 723, width = 103, height = 179 },
				spriteSourceSize = { width = 103, height = 179 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_003.png",
				spriteColorRect = { x = 122, y = 100, width = 105, height = 165 },
				textureRect = { x = 775, y = 278, width = 105, height = 165 },
				spriteSourceSize = { width = 105, height = 165 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_009.png",
				spriteColorRect = { x = 120, y = 101, width = 105, height = 171 },
				textureRect = { x = 163, y = 711, width = 105, height = 171 },
				spriteSourceSize = { width = 105, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_011.png",
				spriteColorRect = { x = 121, y = 101, width = 103, height = 171 },
				textureRect = { x = 906, y = 618, width = 103, height = 171 },
				spriteSourceSize = { width = 103, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_017.png",
				spriteColorRect = { x = 119, y = 93, width = 101, height = 165 },
				textureRect = { x = 630, y = 421, width = 101, height = 165 },
				spriteSourceSize = { width = 101, height = 165 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_025.png",
				spriteColorRect = { x = 124, y = 78, width = 99, height = 179 },
				textureRect = { x = 478, y = 723, width = 99, height = 179 },
				spriteSourceSize = { width = 99, height = 179 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_033.png",
				spriteColorRect = { x = 124, y = 75, width = 99, height = 187 },
				textureRect = { x = 682, y = 771, width = 99, height = 187 },
				spriteSourceSize = { width = 99, height = 187 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_001.png",
				spriteColorRect = { x = 66, y = 106, width = 163, height = 135 },
				textureRect = { x = 614, y = 2, width = 163, height = 135 },
				spriteSourceSize = { width = 163, height = 135 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_003.png",
				spriteColorRect = { x = 67, y = 106, width = 161, height = 137 },
				textureRect = { x = 302, y = 135, width = 161, height = 137 },
				spriteSourceSize = { width = 161, height = 137 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_009.png",
				spriteColorRect = { x = 73, y = 109, width = 155, height = 137 },
				textureRect = { x = 608, y = 139, width = 155, height = 137 },
				spriteSourceSize = { width = 155, height = 137 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_011.png",
				spriteColorRect = { x = 76, y = 109, width = 153, height = 137 },
				textureRect = { x = 765, y = 139, width = 153, height = 137 },
				spriteSourceSize = { width = 153, height = 137 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_017.png",
				spriteColorRect = { x = 82, y = 105, width = 153, height = 127 },
				textureRect = { x = 2, y = 2, width = 153, height = 127 },
				spriteSourceSize = { width = 153, height = 127 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_025.png",
				spriteColorRect = { x = 76, y = 98, width = 167, height = 131 },
				textureRect = { x = 306, y = 2, width = 167, height = 131 },
				spriteSourceSize = { width = 167, height = 131 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_033.png",
				spriteColorRect = { x = 68, y = 98, width = 177, height = 135 },
				textureRect = { x = 779, y = 2, width = 177, height = 135 },
				spriteSourceSize = { width = 177, height = 135 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_001.png",
				spriteColorRect = { x = 126, y = 60, width = 101, height = 175 },
				textureRect = { x = 270, y = 713, width = 101, height = 175 },
				spriteSourceSize = { width = 101, height = 175 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_003.png",
				spriteColorRect = { x = 123, y = 63, width = 105, height = 171 },
				textureRect = { x = 622, y = 588, width = 105, height = 171 },
				spriteSourceSize = { width = 105, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_009.png",
				spriteColorRect = { x = 123, y = 69, width = 103, height = 165 },
				textureRect = { x = 882, y = 306, width = 103, height = 165 },
				spriteSourceSize = { width = 103, height = 165 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_011.png",
				spriteColorRect = { x = 124, y = 70, width = 101, height = 165 },
				textureRect = { x = 920, y = 139, width = 101, height = 165 },
				spriteSourceSize = { width = 101, height = 165 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_017.png",
				spriteColorRect = { x = 123, y = 72, width = 99, height = 169 },
				textureRect = { x = 733, y = 445, width = 99, height = 169 },
				spriteSourceSize = { width = 99, height = 169 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_025.png",
				spriteColorRect = { x = 123, y = 71, width = 101, height = 183 },
				textureRect = { x = 579, y = 761, width = 101, height = 183 },
				spriteSourceSize = { width = 101, height = 183 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_033.png",
				spriteColorRect = { x = 125, y = 64, width = 99, height = 193 },
				textureRect = { x = 783, y = 771, width = 99, height = 193 },
				spriteSourceSize = { width = 99, height = 193 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_001.png",
				spriteColorRect = { x = 74, y = 74, width = 153, height = 155 },
				textureRect = { x = 467, y = 566, width = 153, height = 155 },
				spriteSourceSize = { width = 153, height = 155 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_003.png",
				spriteColorRect = { x = 75, y = 77, width = 151, height = 151 },
				textureRect = { x = 153, y = 558, width = 151, height = 151 },
				spriteSourceSize = { width = 151, height = 151 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_009.png",
				spriteColorRect = { x = 79, y = 85, width = 147, height = 143 },
				textureRect = { x = 149, y = 270, width = 147, height = 143 },
				spriteSourceSize = { width = 147, height = 143 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_011.png",
				spriteColorRect = { x = 81, y = 87, width = 145, height = 141 },
				textureRect = { x = 2, y = 268, width = 145, height = 141 },
				spriteSourceSize = { width = 145, height = 141 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_017.png",
				spriteColorRect = { x = 87, y = 91, width = 141, height = 137 },
				textureRect = { x = 465, y = 135, width = 141, height = 137 },
				spriteSourceSize = { width = 141, height = 137 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_025.png",
				spriteColorRect = { x = 82, y = 90, width = 165, height = 141 },
				textureRect = { x = 608, y = 278, width = 165, height = 141 },
				spriteSourceSize = { width = 165, height = 141 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_033.png",
				spriteColorRect = { x = 74, y = 79, width = 175, height = 151 },
				textureRect = { x = 729, y = 618, width = 175, height = 151 },
				spriteSourceSize = { width = 175, height = 151 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_001.png",
				spriteColorRect = { x = 96, y = 83, width = 159, height = 147 },
				textureRect = { x = 306, y = 564, width = 159, height = 147 },
				spriteSourceSize = { width = 159, height = 147 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_003.png",
				spriteColorRect = { x = 108, y = 86, width = 149, height = 143 },
				textureRect = { x = 834, y = 473, width = 149, height = 143 },
				spriteSourceSize = { width = 149, height = 143 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_009.png",
				spriteColorRect = { x = 117, y = 93, width = 149, height = 135 },
				textureRect = { x = 2, y = 131, width = 149, height = 135 },
				spriteSourceSize = { width = 149, height = 135 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_011.png",
				spriteColorRect = { x = 118, y = 93, width = 147, height = 135 },
				textureRect = { x = 153, y = 133, width = 147, height = 135 },
				spriteSourceSize = { width = 147, height = 135 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_017.png",
				spriteColorRect = { x = 113, y = 98, width = 137, height = 131 },
				textureRect = { x = 475, y = 2, width = 137, height = 131 },
				spriteSourceSize = { width = 137, height = 131 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_025.png",
				spriteColorRect = { x = 93, y = 98, width = 155, height = 143 },
				textureRect = { x = 310, y = 419, width = 155, height = 143 },
				spriteSourceSize = { width = 155, height = 143 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_033.png",
				spriteColorRect = { x = 92, y = 87, width = 159, height = 155 },
				textureRect = { x = 2, y = 711, width = 159, height = 155 },
				spriteSourceSize = { width = 159, height = 155 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_001.png",
				spriteColorRect = { x = 94, y = 102, width = 161, height = 143 },
				textureRect = { x = 467, y = 421, width = 161, height = 143 },
				spriteSourceSize = { width = 161, height = 143 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_003.png",
				spriteColorRect = { x = 112, y = 106, width = 145, height = 143 },
				textureRect = { x = 2, y = 411, width = 145, height = 143 },
				spriteSourceSize = { width = 145, height = 143 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_009.png",
				spriteColorRect = { x = 117, y = 108, width = 149, height = 145 },
				textureRect = { x = 2, y = 558, width = 149, height = 145 },
				spriteSourceSize = { width = 149, height = 145 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_011.png",
				spriteColorRect = { x = 117, y = 110, width = 149, height = 143 },
				textureRect = { x = 457, y = 274, width = 149, height = 143 },
				spriteSourceSize = { width = 149, height = 143 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_017.png",
				spriteColorRect = { x = 103, y = 108, width = 147, height = 129 },
				textureRect = { x = 157, y = 2, width = 147, height = 129 },
				spriteSourceSize = { width = 147, height = 129 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_025.png",
				spriteColorRect = { x = 91, y = 96, width = 157, height = 139 },
				textureRect = { x = 298, y = 274, width = 157, height = 139 },
				spriteSourceSize = { width = 157, height = 139 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_033.png",
				spriteColorRect = { x = 92, y = 97, width = 159, height = 141 },
				textureRect = { x = 149, y = 415, width = 159, height = 141 },
				spriteSourceSize = { width = 159, height = 141 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

