-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:e92057f24baaa4bcb302b0593a29430c$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "run-160_rgb_001.png",
				spriteColorRect = { x = 62, y = 99, width = 152, height = 126 },
				textureRect = { x = 792, y = 586, width = 152, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_003.png",
				spriteColorRect = { x = 63, y = 99, width = 150, height = 128 },
				textureRect = { x = 584, y = 712, width = 150, height = 128 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_009.png",
				spriteColorRect = { x = 69, y = 102, width = 144, height = 128 },
				textureRect = { x = 882, y = 716, width = 144, height = 128 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_011.png",
				spriteColorRect = { x = 70, y = 102, width = 144, height = 128 },
				textureRect = { x = 736, y = 714, width = 144, height = 128 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_017.png",
				spriteColorRect = { x = 77, y = 99, width = 142, height = 118 },
				textureRect = { x = 1278, y = 220, width = 142, height = 118 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_025.png",
				spriteColorRect = { x = 71, y = 92, width = 156, height = 122 },
				textureRect = { x = 820, y = 338, width = 156, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-160_rgb_033.png",
				spriteColorRect = { x = 63, y = 92, width = 166, height = 126 },
				textureRect = { x = 946, y = 588, width = 166, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_001.png",
				spriteColorRect = { x = 70, y = 70, width = 142, height = 144 },
				textureRect = { x = 680, y = 1814, width = 142, height = 144 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_003.png",
				spriteColorRect = { x = 69, y = 71, width = 142, height = 142 },
				textureRect = { x = 1904, y = 1562, width = 142, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_009.png",
				spriteColorRect = { x = 73, y = 79, width = 138, height = 134 },
				textureRect = { x = 142, y = 1102, width = 138, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_011.png",
				spriteColorRect = { x = 77, y = 81, width = 134, height = 132 },
				textureRect = { x = 2, y = 830, width = 134, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_017.png",
				spriteColorRect = { x = 81, y = 85, width = 132, height = 128 },
				textureRect = { x = 1028, y = 716, width = 132, height = 128 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_025.png",
				spriteColorRect = { x = 77, y = 84, width = 154, height = 132 },
				textureRect = { x = 138, y = 834, width = 154, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-220_rgb_033.png",
				spriteColorRect = { x = 70, y = 73, width = 162, height = 142 },
				textureRect = { x = 546, y = 1670, width = 162, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_001.png",
				spriteColorRect = { x = 88, y = 79, width = 150, height = 136 },
				textureRect = { x = 1314, y = 1124, width = 150, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_003.png",
				spriteColorRect = { x = 102, y = 80, width = 138, height = 134 },
				textureRect = { x = 2, y = 1102, width = 138, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_009.png",
				spriteColorRect = { x = 110, y = 87, width = 138, height = 126 },
				textureRect = { x = 1360, y = 592, width = 138, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_011.png",
				spriteColorRect = { x = 110, y = 87, width = 138, height = 126 },
				textureRect = { x = 1114, y = 588, width = 138, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_017.png",
				spriteColorRect = { x = 105, y = 92, width = 128, height = 122 },
				textureRect = { x = 978, y = 340, width = 128, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_025.png",
				spriteColorRect = { x = 86, y = 91, width = 146, height = 134 },
				textureRect = { x = 392, y = 1106, width = 146, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-330_rgb_033.png",
				spriteColorRect = { x = 86, y = 82, width = 148, height = 144 },
				textureRect = { x = 1238, y = 1830, width = 148, height = 144 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_001.png",
				spriteColorRect = { x = 88, y = 95, width = 150, height = 134 },
				textureRect = { x = 1760, y = 1002, width = 150, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_003.png",
				spriteColorRect = { x = 106, y = 99, width = 134, height = 134 },
				textureRect = { x = 1912, y = 868, width = 134, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_009.png",
				spriteColorRect = { x = 109, y = 101, width = 140, height = 136 },
				textureRect = { x = 800, y = 1114, width = 140, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_011.png",
				spriteColorRect = { x = 110, y = 103, width = 138, height = 134 },
				textureRect = { x = 1472, y = 990, width = 138, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_017.png",
				spriteColorRect = { x = 95, y = 100, width = 138, height = 122 },
				textureRect = { x = 1108, y = 340, width = 138, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_025.png",
				spriteColorRect = { x = 86, y = 91, width = 146, height = 128 },
				textureRect = { x = 1162, y = 718, width = 146, height = 128 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "run-390_rgb_033.png",
				spriteColorRect = { x = 86, y = 91, width = 148, height = 132 },
				textureRect = { x = 650, y = 978, width = 148, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_077.png",
				spriteColorRect = { x = 100, y = 28, width = 128, height = 142 },
				textureRect = { x = 710, y = 1670, width = 128, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_081.png",
				spriteColorRect = { x = 100, y = 28, width = 128, height = 142 },
				textureRect = { x = 416, y = 1668, width = 128, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_085.png",
				spriteColorRect = { x = 98, y = 28, width = 130, height = 142 },
				textureRect = { x = 840, y = 1674, width = 130, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_089.png",
				spriteColorRect = { x = 102, y = 29, width = 126, height = 140 },
				textureRect = { x = 302, y = 1520, width = 126, height = 140 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_093.png",
				spriteColorRect = { x = 102, y = 29, width = 126, height = 140 },
				textureRect = { x = 1638, y = 1416, width = 126, height = 140 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_097.png",
				spriteColorRect = { x = 104, y = 28, width = 124, height = 138 },
				textureRect = { x = 1904, y = 1142, width = 124, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_101.png",
				spriteColorRect = { x = 102, y = 28, width = 126, height = 136 },
				textureRect = { x = 1912, y = 1004, width = 126, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_105.png",
				spriteColorRect = { x = 116, y = 28, width = 106, height = 140 },
				textureRect = { x = 1530, y = 1404, width = 106, height = 140 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_109.png",
				spriteColorRect = { x = 118, y = 29, width = 102, height = 138 },
				textureRect = { x = 1800, y = 1138, width = 102, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_113.png",
				spriteColorRect = { x = 119, y = 29, width = 100, height = 138 },
				textureRect = { x = 252, y = 1240, width = 100, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_117.png",
				spriteColorRect = { x = 119, y = 28, width = 100, height = 142 },
				textureRect = { x = 1766, y = 1418, width = 100, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_121.png",
				spriteColorRect = { x = 119, y = 29, width = 100, height = 138 },
				textureRect = { x = 150, y = 1238, width = 100, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_265.png",
				spriteColorRect = { x = 105, y = 29, width = 118, height = 138 },
				textureRect = { x = 1526, y = 1264, width = 118, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_269.png",
				spriteColorRect = { x = 105, y = 29, width = 118, height = 138 },
				textureRect = { x = 1406, y = 1264, width = 118, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_273.png",
				spriteColorRect = { x = 105, y = 29, width = 118, height = 138 },
				textureRect = { x = 1286, y = 1262, width = 118, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_277.png",
				spriteColorRect = { x = 103, y = 28, width = 120, height = 138 },
				textureRect = { x = 1164, y = 1256, width = 120, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_281.png",
				spriteColorRect = { x = 105, y = 28, width = 118, height = 138 },
				textureRect = { x = 1044, y = 1256, width = 118, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_285.png",
				spriteColorRect = { x = 105, y = 28, width = 118, height = 138 },
				textureRect = { x = 924, y = 1254, width = 118, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_289.png",
				spriteColorRect = { x = 102, y = 29, width = 118, height = 138 },
				textureRect = { x = 654, y = 1250, width = 118, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_293.png",
				spriteColorRect = { x = 101, y = 28, width = 122, height = 138 },
				textureRect = { x = 1646, y = 1276, width = 122, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_299.png",
				spriteColorRect = { x = 99, y = 29, width = 120, height = 140 },
				textureRect = { x = 430, y = 1526, width = 120, height = 140 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_301.png",
				spriteColorRect = { x = 101, y = 29, width = 118, height = 140 },
				textureRect = { x = 1002, y = 1536, width = 118, height = 140 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_371.png",
				spriteColorRect = { x = 111, y = 28, width = 108, height = 136 },
				textureRect = { x = 1466, y = 1126, width = 108, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_375.png",
				spriteColorRect = { x = 107, y = 28, width = 112, height = 134 },
				textureRect = { x = 1186, y = 848, width = 112, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_379.png",
				spriteColorRect = { x = 103, y = 28, width = 116, height = 132 },
				textureRect = { x = 294, y = 834, width = 116, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_383.png",
				spriteColorRect = { x = 111, y = 28, width = 108, height = 130 },
				textureRect = { x = 1418, y = 720, width = 108, height = 130 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_387.png",
				spriteColorRect = { x = 113, y = 29, width = 106, height = 130 },
				textureRect = { x = 1636, y = 724, width = 106, height = 130 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_391.png",
				spriteColorRect = { x = 103, y = 29, width = 116, height = 134 },
				textureRect = { x = 1300, y = 850, width = 116, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_395.png",
				spriteColorRect = { x = 109, y = 28, width = 110, height = 138 },
				textureRect = { x = 1770, y = 1278, width = 110, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_415.png",
				spriteColorRect = { x = 113, y = 29, width = 106, height = 138 },
				textureRect = { x = 108, y = 1378, width = 106, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_419.png",
				spriteColorRect = { x = 115, y = 29, width = 104, height = 138 },
				textureRect = { x = 216, y = 1380, width = 104, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_423.png",
				spriteColorRect = { x = 113, y = 28, width = 106, height = 138 },
				textureRect = { x = 1882, y = 1282, width = 106, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_427.png",
				spriteColorRect = { x = 111, y = 29, width = 108, height = 136 },
				textureRect = { x = 690, y = 1112, width = 108, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_431.png",
				spriteColorRect = { x = 115, y = 28, width = 104, height = 138 },
				textureRect = { x = 2, y = 1376, width = 104, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_435.png",
				spriteColorRect = { x = 107, y = 28, width = 112, height = 136 },
				textureRect = { x = 1050, y = 1118, width = 112, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_439.png",
				spriteColorRect = { x = 113, y = 29, width = 106, height = 136 },
				textureRect = { x = 942, y = 1116, width = 106, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_441.png",
				spriteColorRect = { x = 111, y = 29, width = 108, height = 136 },
				textureRect = { x = 282, y = 1102, width = 108, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_445.png",
				spriteColorRect = { x = 109, y = 28, width = 110, height = 136 },
				textureRect = { x = 1688, y = 1138, width = 110, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_449.png",
				spriteColorRect = { x = 113, y = 29, width = 106, height = 126 },
				textureRect = { x = 1500, y = 592, width = 106, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_453.png",
				spriteColorRect = { x = 113, y = 28, width = 106, height = 128 },
				textureRect = { x = 1310, y = 720, width = 106, height = 128 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_457.png",
				spriteColorRect = { x = 111, y = 28, width = 108, height = 138 },
				textureRect = { x = 322, y = 1380, width = 108, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_461.png",
				spriteColorRect = { x = 113, y = 29, width = 106, height = 140 },
				textureRect = { x = 1284, y = 1402, width = 106, height = 140 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_465.png",
				spriteColorRect = { x = 113, y = 29, width = 106, height = 142 },
				textureRect = { x = 1410, y = 1544, width = 106, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_469.png",
				spriteColorRect = { x = 109, y = 29, width = 110, height = 144 },
				textureRect = { x = 1518, y = 1546, width = 110, height = 144 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_473.png",
				spriteColorRect = { x = 107, y = 28, width = 112, height = 146 },
				textureRect = { x = 302, y = 1662, width = 112, height = 146 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_477.png",
				spriteColorRect = { x = 105, y = 29, width = 114, height = 146 },
				textureRect = { x = 1400, y = 1688, width = 114, height = 146 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_481.png",
				spriteColorRect = { x = 103, y = 29, width = 116, height = 146 },
				textureRect = { x = 296, y = 1810, width = 116, height = 146 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_485.png",
				spriteColorRect = { x = 104, y = 29, width = 118, height = 146 },
				textureRect = { x = 414, y = 1812, width = 118, height = 146 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_489.png",
				spriteColorRect = { x = 103, y = 28, width = 122, height = 146 },
				textureRect = { x = 1114, y = 1822, width = 122, height = 146 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_657.png",
				spriteColorRect = { x = 115, y = 28, width = 104, height = 108 },
				textureRect = { x = 600, y = 108, width = 104, height = 108 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-160_rgb_659.png",
				spriteColorRect = { x = 113, y = 29, width = 106, height = 106 },
				textureRect = { x = 1130, y = 2, width = 106, height = 106 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_077.png",
				spriteColorRect = { x = 123, y = 16, width = 104, height = 134 },
				textureRect = { x = 948, y = 980, width = 104, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_081.png",
				spriteColorRect = { x = 123, y = 16, width = 104, height = 134 },
				textureRect = { x = 544, y = 976, width = 104, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_085.png",
				spriteColorRect = { x = 123, y = 16, width = 104, height = 134 },
				textureRect = { x = 2, y = 964, width = 104, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_089.png",
				spriteColorRect = { x = 123, y = 16, width = 104, height = 134 },
				textureRect = { x = 1524, y = 854, width = 104, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_093.png",
				spriteColorRect = { x = 123, y = 17, width = 104, height = 134 },
				textureRect = { x = 1418, y = 852, width = 104, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_097.png",
				spriteColorRect = { x = 118, y = 16, width = 110, height = 136 },
				textureRect = { x = 1576, y = 1126, width = 110, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_101.png",
				spriteColorRect = { x = 105, y = 17, width = 128, height = 134 },
				textureRect = { x = 1054, y = 982, width = 128, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_105.png",
				spriteColorRect = { x = 103, y = 21, width = 124, height = 122 },
				textureRect = { x = 1374, y = 342, width = 124, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_109.png",
				spriteColorRect = { x = 104, y = 18, width = 124, height = 124 },
				textureRect = { x = 1780, y = 470, width = 124, height = 124 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_113.png",
				spriteColorRect = { x = 104, y = 17, width = 124, height = 124 },
				textureRect = { x = 1360, y = 466, width = 124, height = 124 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_117.png",
				spriteColorRect = { x = 101, y = 16, width = 126, height = 124 },
				textureRect = { x = 1906, y = 482, width = 126, height = 124 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_121.png",
				spriteColorRect = { x = 103, y = 17, width = 124, height = 122 },
				textureRect = { x = 1248, y = 340, width = 124, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_265.png",
				spriteColorRect = { x = 123, y = 17, width = 96, height = 132 },
				textureRect = { x = 562, y = 842, width = 96, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_269.png",
				spriteColorRect = { x = 123, y = 17, width = 96, height = 132 },
				textureRect = { x = 1950, y = 224, width = 96, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_273.png",
				spriteColorRect = { x = 121, y = 16, width = 98, height = 132 },
				textureRect = { x = 760, y = 844, width = 98, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_277.png",
				spriteColorRect = { x = 121, y = 16, width = 98, height = 132 },
				textureRect = { x = 660, y = 844, width = 98, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_281.png",
				spriteColorRect = { x = 119, y = 17, width = 100, height = 132 },
				textureRect = { x = 860, y = 846, width = 100, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_285.png",
				spriteColorRect = { x = 121, y = 17, width = 98, height = 130 },
				textureRect = { x = 2, y = 566, width = 98, height = 130 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_289.png",
				spriteColorRect = { x = 114, y = 16, width = 106, height = 130 },
				textureRect = { x = 1528, y = 722, width = 106, height = 130 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_293.png",
				spriteColorRect = { x = 112, y = 16, width = 110, height = 132 },
				textureRect = { x = 1074, y = 848, width = 110, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_299.png",
				spriteColorRect = { x = 115, y = 16, width = 104, height = 128 },
				textureRect = { x = 1254, y = 588, width = 104, height = 128 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_301.png",
				spriteColorRect = { x = 117, y = 17, width = 102, height = 126 },
				textureRect = { x = 102, y = 574, width = 102, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_371.png",
				spriteColorRect = { x = 119, y = 17, width = 100, height = 122 },
				textureRect = { x = 1048, y = 464, width = 100, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_375.png",
				spriteColorRect = { x = 119, y = 17, width = 100, height = 122 },
				textureRect = { x = 946, y = 464, width = 100, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_379.png",
				spriteColorRect = { x = 117, y = 17, width = 102, height = 122 },
				textureRect = { x = 1150, y = 464, width = 102, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_383.png",
				spriteColorRect = { x = 117, y = 19, width = 102, height = 120 },
				textureRect = { x = 1846, y = 224, width = 102, height = 120 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_387.png",
				spriteColorRect = { x = 117, y = 19, width = 102, height = 120 },
				textureRect = { x = 1526, y = 222, width = 102, height = 120 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_391.png",
				spriteColorRect = { x = 119, y = 17, width = 100, height = 122 },
				textureRect = { x = 626, y = 460, width = 100, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_395.png",
				spriteColorRect = { x = 119, y = 17, width = 100, height = 122 },
				textureRect = { x = 524, y = 460, width = 100, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_415.png",
				spriteColorRect = { x = 117, y = 17, width = 102, height = 122 },
				textureRect = { x = 104, y = 450, width = 102, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_419.png",
				spriteColorRect = { x = 119, y = 17, width = 100, height = 122 },
				textureRect = { x = 2, y = 442, width = 100, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_423.png",
				spriteColorRect = { x = 117, y = 17, width = 102, height = 122 },
				textureRect = { x = 1910, y = 358, width = 102, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_427.png",
				spriteColorRect = { x = 113, y = 17, width = 106, height = 122 },
				textureRect = { x = 728, y = 462, width = 106, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_431.png",
				spriteColorRect = { x = 121, y = 17, width = 98, height = 122 },
				textureRect = { x = 316, y = 456, width = 98, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_435.png",
				spriteColorRect = { x = 113, y = 17, width = 106, height = 122 },
				textureRect = { x = 416, y = 456, width = 106, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_439.png",
				spriteColorRect = { x = 119, y = 17, width = 100, height = 122 },
				textureRect = { x = 1808, y = 346, width = 100, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_441.png",
				spriteColorRect = { x = 119, y = 17, width = 100, height = 122 },
				textureRect = { x = 1706, y = 346, width = 100, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_445.png",
				spriteColorRect = { x = 113, y = 17, width = 106, height = 122 },
				textureRect = { x = 208, y = 456, width = 106, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_449.png",
				spriteColorRect = { x = 107, y = 19, width = 112, height = 120 },
				textureRect = { x = 1630, y = 222, width = 112, height = 120 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_453.png",
				spriteColorRect = { x = 119, y = 19, width = 100, height = 120 },
				textureRect = { x = 1744, y = 224, width = 100, height = 120 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_457.png",
				spriteColorRect = { x = 111, y = 17, width = 108, height = 122 },
				textureRect = { x = 836, y = 462, width = 108, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_461.png",
				spriteColorRect = { x = 119, y = 17, width = 100, height = 122 },
				textureRect = { x = 1500, y = 344, width = 100, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_465.png",
				spriteColorRect = { x = 119, y = 17, width = 100, height = 122 },
				textureRect = { x = 2, y = 318, width = 100, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_469.png",
				spriteColorRect = { x = 117, y = 17, width = 102, height = 122 },
				textureRect = { x = 1602, y = 344, width = 102, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_473.png",
				spriteColorRect = { x = 117, y = 19, width = 102, height = 120 },
				textureRect = { x = 1422, y = 220, width = 102, height = 120 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_477.png",
				spriteColorRect = { x = 116, y = 17, width = 104, height = 122 },
				textureRect = { x = 1254, y = 464, width = 104, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_481.png",
				spriteColorRect = { x = 117, y = 16, width = 108, height = 126 },
				textureRect = { x = 1608, y = 594, width = 108, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_485.png",
				spriteColorRect = { x = 118, y = 16, width = 110, height = 130 },
				textureRect = { x = 1744, y = 724, width = 110, height = 130 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_489.png",
				spriteColorRect = { x = 120, y = 17, width = 110, height = 132 },
				textureRect = { x = 962, y = 846, width = 110, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_657.png",
				spriteColorRect = { x = 121, y = 33, width = 98, height = 106 },
				textureRect = { x = 1338, y = 2, width = 98, height = 106 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-220_rgb_659.png",
				spriteColorRect = { x = 121, y = 33, width = 98, height = 106 },
				textureRect = { x = 1238, y = 2, width = 98, height = 106 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_077.png",
				spriteColorRect = { x = 110, y = 31, width = 142, height = 118 },
				textureRect = { x = 842, y = 218, width = 142, height = 118 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_081.png",
				spriteColorRect = { x = 110, y = 31, width = 144, height = 118 },
				textureRect = { x = 1132, y = 220, width = 144, height = 118 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_085.png",
				spriteColorRect = { x = 110, y = 31, width = 144, height = 118 },
				textureRect = { x = 986, y = 220, width = 144, height = 118 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_089.png",
				spriteColorRect = { x = 111, y = 31, width = 142, height = 118 },
				textureRect = { x = 406, y = 214, width = 142, height = 118 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_093.png",
				spriteColorRect = { x = 110, y = 31, width = 144, height = 118 },
				textureRect = { x = 696, y = 218, width = 144, height = 118 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_097.png",
				spriteColorRect = { x = 110, y = 32, width = 144, height = 118 },
				textureRect = { x = 550, y = 218, width = 144, height = 118 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_101.png",
				spriteColorRect = { x = 110, y = 17, width = 144, height = 142 },
				textureRect = { x = 972, y = 1678, width = 144, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_105.png",
				spriteColorRect = { x = 110, y = 16, width = 140, height = 142 },
				textureRect = { x = 1118, y = 1678, width = 140, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_109.png",
				spriteColorRect = { x = 110, y = 17, width = 142, height = 140 },
				textureRect = { x = 1266, y = 1544, width = 142, height = 140 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_113.png",
				spriteColorRect = { x = 111, y = 16, width = 142, height = 140 },
				textureRect = { x = 1122, y = 1536, width = 142, height = 140 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_117.png",
				spriteColorRect = { x = 112, y = 17, width = 142, height = 138 },
				textureRect = { x = 576, y = 1390, width = 142, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_121.png",
				spriteColorRect = { x = 112, y = 16, width = 142, height = 138 },
				textureRect = { x = 432, y = 1386, width = 142, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_265.png",
				spriteColorRect = { x = 106, y = 21, width = 142, height = 118 },
				textureRect = { x = 262, y = 214, width = 142, height = 118 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_269.png",
				spriteColorRect = { x = 105, y = 19, width = 144, height = 122 },
				textureRect = { x = 1486, y = 468, width = 144, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_273.png",
				spriteColorRect = { x = 106, y = 19, width = 144, height = 124 },
				textureRect = { x = 206, y = 580, width = 144, height = 124 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_277.png",
				spriteColorRect = { x = 106, y = 18, width = 148, height = 126 },
				textureRect = { x = 2, y = 702, width = 148, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_281.png",
				spriteColorRect = { x = 106, y = 19, width = 146, height = 124 },
				textureRect = { x = 352, y = 580, width = 146, height = 124 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_285.png",
				spriteColorRect = { x = 106, y = 19, width = 146, height = 122 },
				textureRect = { x = 1632, y = 470, width = 146, height = 122 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_289.png",
				spriteColorRect = { x = 106, y = 25, width = 142, height = 120 },
				textureRect = { x = 386, y = 334, width = 142, height = 120 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_293.png",
				spriteColorRect = { x = 106, y = 29, width = 136, height = 120 },
				textureRect = { x = 248, y = 334, width = 136, height = 120 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_299.png",
				spriteColorRect = { x = 105, y = 23, width = 142, height = 120 },
				textureRect = { x = 104, y = 328, width = 142, height = 120 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_301.png",
				spriteColorRect = { x = 106, y = 22, width = 138, height = 120 },
				textureRect = { x = 530, y = 338, width = 138, height = 120 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_371.png",
				spriteColorRect = { x = 106, y = 29, width = 148, height = 106 },
				textureRect = { x = 450, y = 106, width = 148, height = 106 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_375.png",
				spriteColorRect = { x = 106, y = 31, width = 148, height = 104 },
				textureRect = { x = 684, y = 2, width = 148, height = 104 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_379.png",
				spriteColorRect = { x = 107, y = 33, width = 146, height = 102 },
				textureRect = { x = 536, y = 2, width = 146, height = 102 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_383.png",
				spriteColorRect = { x = 107, y = 31, width = 146, height = 104 },
				textureRect = { x = 982, y = 2, width = 146, height = 104 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_387.png",
				spriteColorRect = { x = 107, y = 33, width = 146, height = 102 },
				textureRect = { x = 388, y = 2, width = 146, height = 102 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_391.png",
				spriteColorRect = { x = 107, y = 31, width = 146, height = 104 },
				textureRect = { x = 834, y = 2, width = 146, height = 104 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_395.png",
				spriteColorRect = { x = 106, y = 29, width = 148, height = 106 },
				textureRect = { x = 152, y = 104, width = 148, height = 106 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_415.png",
				spriteColorRect = { x = 106, y = 27, width = 148, height = 108 },
				textureRect = { x = 1456, y = 110, width = 148, height = 108 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_419.png",
				spriteColorRect = { x = 106, y = 29, width = 148, height = 106 },
				textureRect = { x = 2, y = 96, width = 148, height = 106 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_423.png",
				spriteColorRect = { x = 106, y = 27, width = 148, height = 108 },
				textureRect = { x = 1306, y = 110, width = 148, height = 108 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_427.png",
				spriteColorRect = { x = 106, y = 27, width = 148, height = 108 },
				textureRect = { x = 1156, y = 110, width = 148, height = 108 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_431.png",
				spriteColorRect = { x = 106, y = 29, width = 148, height = 106 },
				textureRect = { x = 1888, y = 2, width = 148, height = 106 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_435.png",
				spriteColorRect = { x = 106, y = 27, width = 148, height = 108 },
				textureRect = { x = 1006, y = 110, width = 148, height = 108 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_439.png",
				spriteColorRect = { x = 106, y = 29, width = 148, height = 106 },
				textureRect = { x = 1738, y = 2, width = 148, height = 106 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_441.png",
				spriteColorRect = { x = 106, y = 29, width = 148, height = 106 },
				textureRect = { x = 1588, y = 2, width = 148, height = 106 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_445.png",
				spriteColorRect = { x = 106, y = 25, width = 148, height = 110 },
				textureRect = { x = 1606, y = 110, width = 148, height = 110 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_449.png",
				spriteColorRect = { x = 106, y = 29, width = 146, height = 106 },
				textureRect = { x = 302, y = 106, width = 146, height = 106 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_453.png",
				spriteColorRect = { x = 107, y = 35, width = 146, height = 100 },
				textureRect = { x = 240, y = 2, width = 146, height = 100 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_457.png",
				spriteColorRect = { x = 106, y = 23, width = 148, height = 112 },
				textureRect = { x = 1756, y = 110, width = 148, height = 112 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_461.png",
				spriteColorRect = { x = 106, y = 27, width = 148, height = 108 },
				textureRect = { x = 856, y = 108, width = 148, height = 108 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_465.png",
				spriteColorRect = { x = 106, y = 29, width = 148, height = 106 },
				textureRect = { x = 1438, y = 2, width = 148, height = 106 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_469.png",
				spriteColorRect = { x = 106, y = 29, width = 148, height = 108 },
				textureRect = { x = 706, y = 108, width = 148, height = 108 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_473.png",
				spriteColorRect = { x = 106, y = 29, width = 148, height = 114 },
				textureRect = { x = 112, y = 212, width = 148, height = 114 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_477.png",
				spriteColorRect = { x = 106, y = 29, width = 148, height = 120 },
				textureRect = { x = 670, y = 338, width = 148, height = 120 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_481.png",
				spriteColorRect = { x = 106, y = 30, width = 148, height = 124 },
				textureRect = { x = 500, y = 584, width = 148, height = 124 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_485.png",
				spriteColorRect = { x = 106, y = 29, width = 146, height = 126 },
				textureRect = { x = 1868, y = 608, width = 146, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_489.png",
				spriteColorRect = { x = 105, y = 29, width = 148, height = 126 },
				textureRect = { x = 1718, y = 596, width = 148, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_657.png",
				spriteColorRect = { x = 110, y = 44, width = 118, height = 92 },
				textureRect = { x = 2, y = 2, width = 118, height = 92 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-330_rgb_659.png",
				spriteColorRect = { x = 111, y = 44, width = 116, height = 92 },
				textureRect = { x = 122, y = 2, width = 116, height = 92 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_077.png",
				spriteColorRect = { x = 109, y = 31, width = 140, height = 138 },
				textureRect = { x = 862, y = 1394, width = 140, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_081.png",
				spriteColorRect = { x = 109, y = 31, width = 140, height = 138 },
				textureRect = { x = 720, y = 1390, width = 140, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_085.png",
				spriteColorRect = { x = 110, y = 32, width = 138, height = 138 },
				textureRect = { x = 1868, y = 1422, width = 138, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_089.png",
				spriteColorRect = { x = 110, y = 31, width = 138, height = 138 },
				textureRect = { x = 1144, y = 1396, width = 138, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_093.png",
				spriteColorRect = { x = 111, y = 32, width = 136, height = 138 },
				textureRect = { x = 1392, y = 1404, width = 136, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_097.png",
				spriteColorRect = { x = 111, y = 31, width = 132, height = 140 },
				textureRect = { x = 1630, y = 1558, width = 132, height = 140 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_101.png",
				spriteColorRect = { x = 110, y = 31, width = 140, height = 132 },
				textureRect = { x = 108, y = 968, width = 140, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_105.png",
				spriteColorRect = { x = 110, y = 31, width = 144, height = 144 },
				textureRect = { x = 534, y = 1814, width = 144, height = 144 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_109.png",
				spriteColorRect = { x = 110, y = 32, width = 142, height = 144 },
				textureRect = { x = 2, y = 1800, width = 142, height = 144 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_113.png",
				spriteColorRect = { x = 111, y = 31, width = 140, height = 146 },
				textureRect = { x = 1676, y = 1850, width = 140, height = 146 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_117.png",
				spriteColorRect = { x = 110, y = 32, width = 144, height = 146 },
				textureRect = { x = 1530, y = 1848, width = 144, height = 146 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_121.png",
				spriteColorRect = { x = 111, y = 32, width = 140, height = 146 },
				textureRect = { x = 1388, y = 1844, width = 140, height = 146 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_265.png",
				spriteColorRect = { x = 105, y = 32, width = 138, height = 138 },
				textureRect = { x = 1004, y = 1396, width = 138, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_269.png",
				spriteColorRect = { x = 105, y = 32, width = 138, height = 140 },
				textureRect = { x = 1764, y = 1562, width = 138, height = 140 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_273.png",
				spriteColorRect = { x = 105, y = 31, width = 138, height = 142 },
				textureRect = { x = 1516, y = 1700, width = 138, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_277.png",
				spriteColorRect = { x = 105, y = 31, width = 138, height = 146 },
				textureRect = { x = 1818, y = 1850, width = 138, height = 146 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_281.png",
				spriteColorRect = { x = 105, y = 31, width = 138, height = 144 },
				textureRect = { x = 824, y = 1818, width = 138, height = 144 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_285.png",
				spriteColorRect = { x = 105, y = 32, width = 138, height = 142 },
				textureRect = { x = 1260, y = 1686, width = 138, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_289.png",
				spriteColorRect = { x = 105, y = 31, width = 138, height = 134 },
				textureRect = { x = 1332, y = 988, width = 138, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_293.png",
				spriteColorRect = { x = 105, y = 31, width = 138, height = 132 },
				textureRect = { x = 1772, y = 868, width = 138, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_299.png",
				spriteColorRect = { x = 106, y = 31, width = 140, height = 132 },
				textureRect = { x = 1630, y = 856, width = 140, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_301.png",
				spriteColorRect = { x = 105, y = 32, width = 142, height = 130 },
				textureRect = { x = 1856, y = 736, width = 142, height = 130 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_371.png",
				spriteColorRect = { x = 107, y = 32, width = 146, height = 136 },
				textureRect = { x = 2, y = 1238, width = 146, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_375.png",
				spriteColorRect = { x = 106, y = 32, width = 146, height = 134 },
				textureRect = { x = 1612, y = 990, width = 146, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_379.png",
				spriteColorRect = { x = 106, y = 31, width = 144, height = 132 },
				textureRect = { x = 250, y = 968, width = 144, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_383.png",
				spriteColorRect = { x = 106, y = 32, width = 142, height = 126 },
				textureRect = { x = 440, y = 710, width = 142, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_387.png",
				spriteColorRect = { x = 107, y = 32, width = 142, height = 126 },
				textureRect = { x = 296, y = 706, width = 142, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_391.png",
				spriteColorRect = { x = 107, y = 31, width = 146, height = 132 },
				textureRect = { x = 1184, y = 986, width = 146, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_395.png",
				spriteColorRect = { x = 106, y = 31, width = 148, height = 138 },
				textureRect = { x = 852, y = 1534, width = 148, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_415.png",
				spriteColorRect = { x = 106, y = 31, width = 148, height = 134 },
				textureRect = { x = 1164, y = 1120, width = 148, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_419.png",
				spriteColorRect = { x = 106, y = 32, width = 148, height = 136 },
				textureRect = { x = 774, y = 1252, width = 148, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_423.png",
				spriteColorRect = { x = 106, y = 31, width = 148, height = 134 },
				textureRect = { x = 540, y = 1112, width = 148, height = 134 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_427.png",
				spriteColorRect = { x = 106, y = 32, width = 148, height = 132 },
				textureRect = { x = 412, y = 838, width = 148, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_431.png",
				spriteColorRect = { x = 106, y = 31, width = 148, height = 138 },
				textureRect = { x = 702, y = 1530, width = 148, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_435.png",
				spriteColorRect = { x = 107, y = 31, width = 146, height = 132 },
				textureRect = { x = 800, y = 980, width = 146, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_439.png",
				spriteColorRect = { x = 106, y = 31, width = 148, height = 138 },
				textureRect = { x = 552, y = 1530, width = 148, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_441.png",
				spriteColorRect = { x = 106, y = 31, width = 148, height = 138 },
				textureRect = { x = 152, y = 1520, width = 148, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_445.png",
				spriteColorRect = { x = 106, y = 32, width = 146, height = 132 },
				textureRect = { x = 396, y = 972, width = 146, height = 132 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_449.png",
				spriteColorRect = { x = 107, y = 32, width = 140, height = 124 },
				textureRect = { x = 650, y = 586, width = 140, height = 124 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_453.png",
				spriteColorRect = { x = 106, y = 31, width = 142, height = 126 },
				textureRect = { x = 152, y = 706, width = 142, height = 126 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_457.png",
				spriteColorRect = { x = 105, y = 32, width = 148, height = 136 },
				textureRect = { x = 504, y = 1248, width = 148, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_461.png",
				spriteColorRect = { x = 106, y = 32, width = 148, height = 140 },
				textureRect = { x = 152, y = 1660, width = 148, height = 140 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_465.png",
				spriteColorRect = { x = 106, y = 32, width = 148, height = 142 },
				textureRect = { x = 1806, y = 1706, width = 148, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_469.png",
				spriteColorRect = { x = 106, y = 32, width = 148, height = 144 },
				textureRect = { x = 964, y = 1822, width = 148, height = 144 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_473.png",
				spriteColorRect = { x = 106, y = 31, width = 148, height = 144 },
				textureRect = { x = 146, y = 1802, width = 148, height = 144 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_477.png",
				spriteColorRect = { x = 106, y = 32, width = 148, height = 142 },
				textureRect = { x = 1656, y = 1704, width = 148, height = 142 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_481.png",
				spriteColorRect = { x = 106, y = 32, width = 148, height = 140 },
				textureRect = { x = 2, y = 1658, width = 148, height = 140 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_485.png",
				spriteColorRect = { x = 106, y = 32, width = 148, height = 136 },
				textureRect = { x = 354, y = 1242, width = 148, height = 136 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_489.png",
				spriteColorRect = { x = 106, y = 31, width = 148, height = 138 },
				textureRect = { x = 2, y = 1518, width = 148, height = 138 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_657.png",
				spriteColorRect = { x = 110, y = 32, width = 110, height = 112 },
				textureRect = { x = 1906, y = 110, width = 110, height = 112 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sit-390_rgb_659.png",
				spriteColorRect = { x = 111, y = 32, width = 108, height = 112 },
				textureRect = { x = 2, y = 204, width = 108, height = 112 },
				spriteSourceSize = { width = 272, height = 272 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

