-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:984f689077d98f6e7271f29d02d8e95b$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "run-0_rgb_001.png",
				spriteColorRect = { x = 112, y = 88, width = 105, height = 169 },
				textureRect = { x = 101, y = 2, width = 105, height = 169 },
				spriteSourceSize = { width = 105, height = 169 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_003.png",
				spriteColorRect = { x = 111, y = 106, width = 105, height = 149 },
				textureRect = { x = 109, y = 529, width = 105, height = 149 },
				spriteSourceSize = { width = 105, height = 149 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_009.png",
				spriteColorRect = { x = 109, y = 108, width = 105, height = 155 },
				textureRect = { x = 103, y = 700, width = 105, height = 155 },
				spriteSourceSize = { width = 105, height = 155 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_011.png",
				spriteColorRect = { x = 110, y = 109, width = 103, height = 153 },
				textureRect = { x = 208, y = 857, width = 103, height = 153 },
				spriteSourceSize = { width = 103, height = 153 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_017.png",
				spriteColorRect = { x = 107, y = 103, width = 103, height = 145 },
				textureRect = { x = 206, y = 320, width = 103, height = 145 },
				spriteSourceSize = { width = 103, height = 145 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_025.png",
				spriteColorRect = { x = 113, y = 84, width = 99, height = 163 },
				textureRect = { x = 105, y = 173, width = 99, height = 163 },
				spriteSourceSize = { width = 99, height = 163 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_033.png",
				spriteColorRect = { x = 115, y = 83, width = 97, height = 169 },
				textureRect = { x = 2, y = 364, width = 97, height = 169 },
				spriteSourceSize = { width = 97, height = 169 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_001.png",
				spriteColorRect = { x = 57, y = 105, width = 161, height = 127 },
				textureRect = { x = 794, y = 240, width = 161, height = 127 },
				spriteSourceSize = { width = 161, height = 127 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_003.png",
				spriteColorRect = { x = 57, y = 113, width = 161, height = 121 },
				textureRect = { x = 794, y = 369, width = 161, height = 121 },
				spriteSourceSize = { width = 161, height = 121 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_009.png",
				spriteColorRect = { x = 62, y = 113, width = 155, height = 123 },
				textureRect = { x = 629, y = 385, width = 155, height = 123 },
				spriteSourceSize = { width = 155, height = 123 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_011.png",
				spriteColorRect = { x = 65, y = 113, width = 153, height = 123 },
				textureRect = { x = 794, y = 492, width = 153, height = 123 },
				spriteSourceSize = { width = 153, height = 123 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_017.png",
				spriteColorRect = { x = 72, y = 104, width = 151, height = 119 },
				textureRect = { x = 359, y = 2, width = 151, height = 119 },
				spriteSourceSize = { width = 151, height = 119 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_025.png",
				spriteColorRect = { x = 66, y = 105, width = 165, height = 115 },
				textureRect = { x = 794, y = 123, width = 165, height = 115 },
				spriteSourceSize = { width = 165, height = 115 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_033.png",
				spriteColorRect = { x = 57, y = 105, width = 177, height = 119 },
				textureRect = { x = 794, y = 2, width = 177, height = 119 },
				spriteSourceSize = { width = 177, height = 119 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_001.png",
				spriteColorRect = { x = 114, y = 62, width = 103, height = 163 },
				textureRect = { x = 101, y = 364, width = 103, height = 163 },
				spriteSourceSize = { width = 103, height = 163 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_003.png",
				spriteColorRect = { x = 112, y = 62, width = 105, height = 163 },
				textureRect = { x = 2, y = 535, width = 105, height = 163 },
				spriteSourceSize = { width = 105, height = 163 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_009.png",
				spriteColorRect = { x = 113, y = 67, width = 101, height = 157 },
				textureRect = { x = 2, y = 861, width = 101, height = 157 },
				spriteSourceSize = { width = 101, height = 157 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_011.png",
				spriteColorRect = { x = 112, y = 70, width = 101, height = 155 },
				textureRect = { x = 105, y = 857, width = 101, height = 155 },
				spriteSourceSize = { width = 101, height = 155 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_017.png",
				spriteColorRect = { x = 112, y = 72, width = 99, height = 159 },
				textureRect = { x = 2, y = 700, width = 99, height = 159 },
				spriteSourceSize = { width = 99, height = 159 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_025.png",
				spriteColorRect = { x = 112, y = 71, width = 101, height = 173 },
				textureRect = { x = 2, y = 189, width = 101, height = 173 },
				spriteSourceSize = { width = 101, height = 173 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_033.png",
				spriteColorRect = { x = 115, y = 62, width = 97, height = 185 },
				textureRect = { x = 2, y = 2, width = 97, height = 185 },
				spriteSourceSize = { width = 97, height = 185 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_001.png",
				spriteColorRect = { x = 64, y = 75, width = 151, height = 145 },
				textureRect = { x = 206, y = 173, width = 151, height = 145 },
				spriteSourceSize = { width = 151, height = 145 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_003.png",
				spriteColorRect = { x = 65, y = 75, width = 149, height = 145 },
				textureRect = { x = 208, y = 2, width = 149, height = 145 },
				spriteSourceSize = { width = 149, height = 145 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_009.png",
				spriteColorRect = { x = 69, y = 80, width = 145, height = 139 },
				textureRect = { x = 371, y = 612, width = 145, height = 139 },
				spriteSourceSize = { width = 145, height = 139 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_011.png",
				spriteColorRect = { x = 71, y = 82, width = 143, height = 137 },
				textureRect = { x = 488, y = 753, width = 143, height = 137 },
				spriteSourceSize = { width = 143, height = 137 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_017.png",
				spriteColorRect = { x = 76, y = 86, width = 141, height = 133 },
				textureRect = { x = 359, y = 123, width = 141, height = 133 },
				spriteSourceSize = { width = 141, height = 133 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_025.png",
				spriteColorRect = { x = 71, y = 82, width = 165, height = 139 },
				textureRect = { x = 311, y = 320, width = 165, height = 139 },
				spriteSourceSize = { width = 165, height = 139 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_033.png",
				spriteColorRect = { x = 64, y = 76, width = 173, height = 145 },
				textureRect = { x = 313, y = 829, width = 173, height = 145 },
				spriteSourceSize = { width = 173, height = 145 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_001.png",
				spriteColorRect = { x = 83, y = 85, width = 161, height = 135 },
				textureRect = { x = 518, y = 600, width = 161, height = 135 },
				spriteSourceSize = { width = 161, height = 135 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_003.png",
				spriteColorRect = { x = 98, y = 85, width = 147, height = 135 },
				textureRect = { x = 633, y = 737, width = 147, height = 135 },
				spriteSourceSize = { width = 147, height = 135 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_009.png",
				spriteColorRect = { x = 105, y = 88, width = 149, height = 131 },
				textureRect = { x = 794, y = 617, width = 149, height = 131 },
				spriteSourceSize = { width = 149, height = 131 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_011.png",
				spriteColorRect = { x = 105, y = 88, width = 149, height = 131 },
				textureRect = { x = 502, y = 123, width = 149, height = 131 },
				spriteSourceSize = { width = 149, height = 131 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_017.png",
				spriteColorRect = { x = 100, y = 93, width = 139, height = 127 },
				textureRect = { x = 653, y = 123, width = 139, height = 127 },
				spriteSourceSize = { width = 139, height = 127 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_025.png",
				spriteColorRect = { x = 81, y = 89, width = 155, height = 143 },
				textureRect = { x = 216, y = 467, width = 155, height = 143 },
				spriteSourceSize = { width = 155, height = 143 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_033.png",
				spriteColorRect = { x = 81, y = 85, width = 159, height = 147 },
				textureRect = { x = 210, y = 680, width = 159, height = 147 },
				spriteSourceSize = { width = 159, height = 147 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_001.png",
				spriteColorRect = { x = 83, y = 99, width = 161, height = 137 },
				textureRect = { x = 373, y = 461, width = 161, height = 137 },
				spriteSourceSize = { width = 161, height = 137 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_003.png",
				spriteColorRect = { x = 102, y = 107, width = 143, height = 133 },
				textureRect = { x = 649, y = 874, width = 143, height = 133 },
				spriteSourceSize = { width = 143, height = 133 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_009.png",
				spriteColorRect = { x = 106, y = 113, width = 149, height = 131 },
				textureRect = { x = 478, y = 258, width = 149, height = 131 },
				spriteSourceSize = { width = 149, height = 131 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_011.png",
				spriteColorRect = { x = 105, y = 115, width = 149, height = 129 },
				textureRect = { x = 794, y = 750, width = 149, height = 129 },
				spriteSourceSize = { width = 149, height = 129 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_017.png",
				spriteColorRect = { x = 90, y = 109, width = 149, height = 119 },
				textureRect = { x = 512, y = 2, width = 149, height = 119 },
				spriteSourceSize = { width = 149, height = 119 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_025.png",
				spriteColorRect = { x = 80, y = 98, width = 157, height = 127 },
				textureRect = { x = 629, y = 256, width = 157, height = 127 },
				spriteSourceSize = { width = 157, height = 127 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_033.png",
				spriteColorRect = { x = 81, y = 99, width = 159, height = 129 },
				textureRect = { x = 488, y = 892, width = 159, height = 129 },
				spriteSourceSize = { width = 159, height = 129 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

