-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:1c111223f71c78c3fb3c94f14117df8a$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "run-0_rgb_001.png",
				spriteColorRect = { x = 139, y = 114, width = 104, height = 168 },
				textureRect = { x = 2, y = 566, width = 104, height = 168 },
				spriteSourceSize = { width = 104, height = 168 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_003.png",
				spriteColorRect = { x = 138, y = 132, width = 104, height = 148 },
				textureRect = { x = 456, y = 820, width = 104, height = 148 },
				spriteSourceSize = { width = 104, height = 148 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_009.png",
				spriteColorRect = { x = 136, y = 134, width = 104, height = 154 },
				textureRect = { x = 402, y = 660, width = 104, height = 154 },
				spriteSourceSize = { width = 104, height = 154 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_011.png",
				spriteColorRect = { x = 136, y = 134, width = 104, height = 154 },
				textureRect = { x = 916, y = 804, width = 104, height = 154 },
				spriteSourceSize = { width = 104, height = 154 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_017.png",
				spriteColorRect = { x = 134, y = 127, width = 102, height = 146 },
				textureRect = { x = 562, y = 822, width = 102, height = 146 },
				spriteSourceSize = { width = 102, height = 146 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_025.png",
				spriteColorRect = { x = 138, y = 110, width = 100, height = 162 },
				textureRect = { x = 814, y = 804, width = 100, height = 162 },
				spriteSourceSize = { width = 100, height = 162 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_033.png",
				spriteColorRect = { x = 140, y = 110, width = 98, height = 168 },
				textureRect = { x = 714, y = 768, width = 98, height = 168 },
				spriteSourceSize = { width = 98, height = 168 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_001.png",
				spriteColorRect = { x = 82, y = 131, width = 162, height = 126 },
				textureRect = { x = 318, y = 282, width = 162, height = 126 },
				spriteSourceSize = { width = 162, height = 126 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_003.png",
				spriteColorRect = { x = 82, y = 137, width = 162, height = 122 },
				textureRect = { x = 812, y = 264, width = 162, height = 122 },
				spriteSourceSize = { width = 162, height = 122 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_009.png",
				spriteColorRect = { x = 89, y = 138, width = 154, height = 124 },
				textureRect = { x = 810, y = 388, width = 154, height = 124 },
				spriteSourceSize = { width = 154, height = 124 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_011.png",
				spriteColorRect = { x = 92, y = 138, width = 152, height = 124 },
				textureRect = { x = 800, y = 514, width = 152, height = 124 },
				spriteSourceSize = { width = 152, height = 124 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_017.png",
				spriteColorRect = { x = 97, y = 128, width = 152, height = 120 },
				textureRect = { x = 456, y = 538, width = 152, height = 120 },
				spriteSourceSize = { width = 152, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_025.png",
				spriteColorRect = { x = 91, y = 131, width = 166, height = 114 },
				textureRect = { x = 632, y = 422, width = 166, height = 114 },
				spriteSourceSize = { width = 166, height = 114 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_033.png",
				spriteColorRect = { x = 82, y = 131, width = 178, height = 118 },
				textureRect = { x = 818, y = 2, width = 178, height = 118 },
				spriteSourceSize = { width = 178, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_001.png",
				spriteColorRect = { x = 141, y = 88, width = 102, height = 162 },
				textureRect = { x = 610, y = 658, width = 102, height = 162 },
				spriteSourceSize = { width = 102, height = 162 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_003.png",
				spriteColorRect = { x = 139, y = 88, width = 104, height = 162 },
				textureRect = { x = 900, y = 640, width = 104, height = 162 },
				spriteSourceSize = { width = 104, height = 162 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_009.png",
				spriteColorRect = { x = 138, y = 93, width = 102, height = 156 },
				textureRect = { x = 248, y = 728, width = 102, height = 156 },
				spriteSourceSize = { width = 102, height = 156 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_011.png",
				spriteColorRect = { x = 138, y = 96, width = 102, height = 154 },
				textureRect = { x = 352, y = 816, width = 102, height = 154 },
				spriteSourceSize = { width = 102, height = 154 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_017.png",
				spriteColorRect = { x = 139, y = 98, width = 98, height = 158 },
				textureRect = { x = 508, y = 660, width = 98, height = 158 },
				spriteSourceSize = { width = 98, height = 158 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_025.png",
				spriteColorRect = { x = 138, y = 96, width = 102, height = 174 },
				textureRect = { x = 144, y = 554, width = 102, height = 174 },
				spriteSourceSize = { width = 102, height = 174 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_033.png",
				spriteColorRect = { x = 141, y = 88, width = 98, height = 184 },
				textureRect = { x = 302, y = 542, width = 98, height = 184 },
				spriteSourceSize = { width = 98, height = 184 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_001.png",
				spriteColorRect = { x = 89, y = 102, width = 152, height = 144 },
				textureRect = { x = 2, y = 150, width = 152, height = 144 },
				spriteSourceSize = { width = 152, height = 144 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_003.png",
				spriteColorRect = { x = 90, y = 101, width = 150, height = 144 },
				textureRect = { x = 666, y = 2, width = 150, height = 144 },
				spriteSourceSize = { width = 150, height = 144 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_009.png",
				spriteColorRect = { x = 94, y = 105, width = 146, height = 140 },
				textureRect = { x = 818, y = 122, width = 146, height = 140 },
				spriteSourceSize = { width = 146, height = 140 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_011.png",
				spriteColorRect = { x = 96, y = 106, width = 144, height = 138 },
				textureRect = { x = 666, y = 148, width = 144, height = 138 },
				spriteSourceSize = { width = 144, height = 138 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_017.png",
				spriteColorRect = { x = 103, y = 111, width = 140, height = 134 },
				textureRect = { x = 2, y = 430, width = 140, height = 134 },
				spriteSourceSize = { width = 140, height = 134 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_025.png",
				spriteColorRect = { x = 97, y = 107, width = 166, height = 140 },
				textureRect = { x = 340, y = 2, width = 166, height = 140 },
				spriteSourceSize = { width = 166, height = 140 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_033.png",
				spriteColorRect = { x = 90, y = 101, width = 174, height = 146 },
				textureRect = { x = 2, y = 2, width = 174, height = 146 },
				spriteSourceSize = { width = 174, height = 146 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_001.png",
				spriteColorRect = { x = 111, y = 110, width = 160, height = 136 },
				textureRect = { x = 156, y = 150, width = 160, height = 136 },
				spriteSourceSize = { width = 160, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_003.png",
				spriteColorRect = { x = 124, y = 111, width = 148, height = 134 },
				textureRect = { x = 156, y = 288, width = 148, height = 134 },
				spriteSourceSize = { width = 148, height = 134 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_009.png",
				spriteColorRect = { x = 132, y = 112, width = 148, height = 132 },
				textureRect = { x = 2, y = 296, width = 148, height = 132 },
				spriteSourceSize = { width = 148, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_011.png",
				spriteColorRect = { x = 132, y = 114, width = 148, height = 130 },
				textureRect = { x = 306, y = 410, width = 148, height = 130 },
				spriteSourceSize = { width = 148, height = 130 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_017.png",
				spriteColorRect = { x = 127, y = 119, width = 138, height = 126 },
				textureRect = { x = 760, y = 640, width = 138, height = 126 },
				spriteSourceSize = { width = 138, height = 126 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_025.png",
				spriteColorRect = { x = 107, y = 115, width = 156, height = 142 },
				textureRect = { x = 508, y = 2, width = 156, height = 142 },
				spriteSourceSize = { width = 156, height = 142 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_033.png",
				spriteColorRect = { x = 106, y = 111, width = 160, height = 146 },
				textureRect = { x = 178, y = 2, width = 160, height = 146 },
				spriteSourceSize = { width = 160, height = 146 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_001.png",
				spriteColorRect = { x = 109, y = 125, width = 162, height = 136 },
				textureRect = { x = 340, y = 144, width = 162, height = 136 },
				spriteSourceSize = { width = 162, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_003.png",
				spriteColorRect = { x = 128, y = 133, width = 144, height = 132 },
				textureRect = { x = 664, y = 288, width = 144, height = 132 },
				spriteSourceSize = { width = 144, height = 132 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_009.png",
				spriteColorRect = { x = 133, y = 140, width = 148, height = 130 },
				textureRect = { x = 482, y = 406, width = 148, height = 130 },
				spriteSourceSize = { width = 148, height = 130 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_011.png",
				spriteColorRect = { x = 132, y = 141, width = 148, height = 128 },
				textureRect = { x = 152, y = 424, width = 148, height = 128 },
				spriteSourceSize = { width = 148, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_017.png",
				spriteColorRect = { x = 117, y = 135, width = 148, height = 118 },
				textureRect = { x = 610, y = 538, width = 148, height = 118 },
				spriteSourceSize = { width = 148, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_025.png",
				spriteColorRect = { x = 106, y = 124, width = 158, height = 126 },
				textureRect = { x = 504, y = 278, width = 158, height = 126 },
				spriteSourceSize = { width = 158, height = 126 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_033.png",
				spriteColorRect = { x = 106, y = 124, width = 160, height = 130 },
				textureRect = { x = 504, y = 146, width = 160, height = 130 },
				spriteSourceSize = { width = 160, height = 130 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

