-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:9758273773b4fdd5c94a6a086ac05751$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "1.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 278, y = 2, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 140, y = 2, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 1796, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 1658, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 1520, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6.png",

				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 1382, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 1244, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "8.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 1106, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "9.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 968, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "10.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 830, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "11.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 692, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "12.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 554, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "13.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 416, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "14.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 278, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "15.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 140, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "16.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 2, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

