-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:f993a1839c8a3568265c5c8da3b70c3b$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "red1.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 278, y = 140, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "red2.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 140, y = 278, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "red3.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 140, y = 140, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "red4.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 278, y = 2, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "red5.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 140, y = 2, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "red6.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 278, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "red7.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 140, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "red8.png",
				spriteColorRect = { x = 0, y = 0, width = 136, height = 136 },
				textureRect = { x = 2, y = 2, width = 136, height = 136 },
				spriteSourceSize = { width = 136, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

