-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:4567ae287096792e8faa90bf7d76915c$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "run-0_rgb_001.png",
				spriteColorRect = { x = 117, y = 82, width = 103, height = 175 },
				textureRect = { x = 2, y = 374, width = 103, height = 175 },
				spriteSourceSize = { width = 103, height = 175 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_003.png",
				spriteColorRect = { x = 115, y = 98, width = 105, height = 157 },
				textureRect = { x = 109, y = 525, width = 105, height = 157 },
				spriteSourceSize = { width = 105, height = 157 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_009.png",
				spriteColorRect = { x = 114, y = 98, width = 103, height = 165 },
				textureRect = { x = 107, y = 358, width = 103, height = 165 },
				spriteSourceSize = { width = 103, height = 165 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_011.png",
				spriteColorRect = { x = 114, y = 98, width = 103, height = 163 },
				textureRect = { x = 206, y = 175, width = 103, height = 163 },
				spriteSourceSize = { width = 103, height = 163 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_017.png",
				spriteColorRect = { x = 112, y = 91, width = 101, height = 157 },
				textureRect = { x = 212, y = 340, width = 101, height = 157 },
				spriteSourceSize = { width = 101, height = 157 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_025.png",
				spriteColorRect = { x = 117, y = 73, width = 99, height = 173 },
				textureRect = { x = 105, y = 183, width = 99, height = 173 },
				spriteSourceSize = { width = 99, height = 173 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-0_rgb_033.png",
				spriteColorRect = { x = 117, y = 73, width = 99, height = 179 },
				textureRect = { x = 103, y = 2, width = 99, height = 179 },
				spriteSourceSize = { width = 99, height = 179 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_001.png",
				spriteColorRect = { x = 59, y = 98, width = 163, height = 133 },
				textureRect = { x = 472, y = 155, width = 163, height = 133 },
				spriteSourceSize = { width = 163, height = 133 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_003.png",
				spriteColorRect = { x = 60, y = 104, width = 161, height = 129 },
				textureRect = { x = 768, y = 276, width = 161, height = 129 },
				spriteSourceSize = { width = 161, height = 129 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_009.png",
				spriteColorRect = { x = 66, y = 105, width = 155, height = 131 },
				textureRect = { x = 475, y = 890, width = 155, height = 131 },
				spriteSourceSize = { width = 155, height = 131 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_011.png",
				spriteColorRect = { x = 69, y = 104, width = 153, height = 131 },
				textureRect = { x = 632, y = 890, width = 153, height = 131 },
				spriteSourceSize = { width = 153, height = 131 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_017.png",
				spriteColorRect = { x = 74, y = 99, width = 153, height = 123 },
				textureRect = { x = 848, y = 407, width = 153, height = 123 },
				spriteSourceSize = { width = 153, height = 123 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_025.png",
				spriteColorRect = { x = 70, y = 95, width = 165, height = 123 },
				textureRect = { x = 787, y = 133, width = 165, height = 123 },
				spriteSourceSize = { width = 165, height = 123 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-160_rgb_033.png",
				spriteColorRect = { x = 61, y = 94, width = 177, height = 129 },
				textureRect = { x = 787, y = 2, width = 177, height = 129 },
				spriteSourceSize = { width = 177, height = 129 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_001.png",
				spriteColorRect = { x = 119, y = 54, width = 101, height = 171 },
				textureRect = { x = 204, y = 2, width = 101, height = 171 },
				spriteSourceSize = { width = 101, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_003.png",
				spriteColorRect = { x = 116, y = 55, width = 105, height = 169 },
				textureRect = { x = 2, y = 551, width = 105, height = 169 },
				spriteSourceSize = { width = 105, height = 169 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_009.png",
				spriteColorRect = { x = 117, y = 63, width = 101, height = 161 },
				textureRect = { x = 105, y = 722, width = 101, height = 161 },
				spriteSourceSize = { width = 101, height = 161 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_011.png",
				spriteColorRect = { x = 116, y = 64, width = 101, height = 161 },
				textureRect = { x = 2, y = 722, width = 101, height = 161 },
				spriteSourceSize = { width = 101, height = 161 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_017.png",
				spriteColorRect = { x = 116, y = 68, width = 99, height = 163 },
				textureRect = { x = 307, y = 2, width = 99, height = 163 },
				spriteSourceSize = { width = 99, height = 163 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_025.png",
				spriteColorRect = { x = 116, y = 64, width = 101, height = 179 },
				textureRect = { x = 2, y = 193, width = 101, height = 179 },
				spriteSourceSize = { width = 101, height = 179 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-180_rgb_033.png",
				spriteColorRect = { x = 118, y = 57, width = 99, height = 189 },
				textureRect = { x = 2, y = 2, width = 99, height = 189 },
				spriteSourceSize = { width = 99, height = 189 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_001.png",
				spriteColorRect = { x = 68, y = 68, width = 151, height = 151 },
				textureRect = { x = 408, y = 2, width = 151, height = 151 },
				spriteSourceSize = { width = 151, height = 151 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_003.png",
				spriteColorRect = { x = 67, y = 71, width = 151, height = 147 },
				textureRect = { x = 216, y = 499, width = 151, height = 147 },
				spriteSourceSize = { width = 151, height = 147 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_009.png",
				spriteColorRect = { x = 73, y = 77, width = 145, height = 141 },
				textureRect = { x = 369, y = 465, width = 145, height = 141 },
				spriteSourceSize = { width = 145, height = 141 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_011.png",
				spriteColorRect = { x = 75, y = 79, width = 143, height = 139 },
				textureRect = { x = 516, y = 431, width = 143, height = 139 },
				spriteSourceSize = { width = 143, height = 139 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_017.png",
				spriteColorRect = { x = 80, y = 85, width = 141, height = 133 },
				textureRect = { x = 661, y = 427, width = 141, height = 133 },
				spriteSourceSize = { width = 141, height = 133 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_025.png",
				spriteColorRect = { x = 75, y = 81, width = 165, height = 139 },
				textureRect = { x = 383, y = 608, width = 165, height = 139 },
				spriteSourceSize = { width = 165, height = 139 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-220_rgb_033.png",
				spriteColorRect = { x = 68, y = 71, width = 173, height = 149 },
				textureRect = { x = 208, y = 684, width = 173, height = 149 },
				spriteSourceSize = { width = 173, height = 149 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_001.png",
				spriteColorRect = { x = 87, y = 79, width = 161, height = 141 },
				textureRect = { x = 312, y = 835, width = 161, height = 141 },
				spriteSourceSize = { width = 161, height = 141 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_003.png",
				spriteColorRect = { x = 102, y = 79, width = 147, height = 139 },
				textureRect = { x = 638, y = 2, width = 147, height = 139 },
				spriteSourceSize = { width = 147, height = 139 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_009.png",
				spriteColorRect = { x = 111, y = 86, width = 147, height = 131 },
				textureRect = { x = 638, y = 143, width = 147, height = 131 },
				spriteSourceSize = { width = 147, height = 131 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_011.png",
				spriteColorRect = { x = 110, y = 88, width = 147, height = 129 },
				textureRect = { x = 638, y = 707, width = 147, height = 129 },
				spriteSourceSize = { width = 147, height = 129 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_017.png",
				spriteColorRect = { x = 105, y = 92, width = 137, height = 127 },
				textureRect = { x = 709, y = 562, width = 137, height = 127 },
				spriteSourceSize = { width = 137, height = 127 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_025.png",
				spriteColorRect = { x = 86, y = 88, width = 155, height = 143 },
				textureRect = { x = 315, y = 320, width = 155, height = 143 },
				spriteSourceSize = { width = 155, height = 143 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-330_rgb_033.png",
				spriteColorRect = { x = 84, y = 80, width = 159, height = 151 },
				textureRect = { x = 311, y = 167, width = 159, height = 151 },
				spriteSourceSize = { width = 159, height = 151 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_001.png",
				spriteColorRect = { x = 87, y = 96, width = 161, height = 139 },
				textureRect = { x = 475, y = 749, width = 161, height = 139 },
				spriteSourceSize = { width = 161, height = 139 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_003.png",
				spriteColorRect = { x = 106, y = 104, width = 143, height = 135 },
				textureRect = { x = 623, y = 290, width = 143, height = 135 },
				spriteSourceSize = { width = 143, height = 135 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_009.png",
				spriteColorRect = { x = 110, y = 104, width = 149, height = 139 },
				textureRect = { x = 472, y = 290, width = 149, height = 139 },
				spriteSourceSize = { width = 149, height = 139 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_011.png",
				spriteColorRect = { x = 111, y = 106, width = 147, height = 137 },
				textureRect = { x = 163, y = 885, width = 147, height = 137 },
				spriteSourceSize = { width = 147, height = 137 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_017.png",
				spriteColorRect = { x = 95, y = 104, width = 147, height = 123 },
				textureRect = { x = 848, y = 532, width = 147, height = 123 },
				spriteSourceSize = { width = 147, height = 123 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_025.png",
				spriteColorRect = { x = 84, y = 92, width = 157, height = 133 },
				textureRect = { x = 550, y = 572, width = 157, height = 133 },
				spriteSourceSize = { width = 157, height = 133 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "run-390_rgb_033.png",
				spriteColorRect = { x = 84, y = 91, width = 159, height = 137 },
				textureRect = { x = 2, y = 885, width = 159, height = 137 },
				spriteSourceSize = { width = 159, height = 137 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

